### ISSUE TITLE
feature req: dtNavMeshQuery::findPathToNearest

### ISSUE THREAD

**Issue by jswigart** [recastnavigation/recastnavigation#10]
Would be very useful to have a function that takes an arbitrary number of positions and poly refs and finds runs a Dijkstra to find the nearest one.

As a bonus, would also be very useful if this function or a variation of this function can generate complete solutions to every destination requested, in order to avoid doing multiple searches when you want to get path distance estimates to many different goals.

**Comment by Janiels** [comment]
Hi @jswigart 
In #211 I added a function which can quickly return solutions to
any polygon explored during the Dijkstra search. Note that you can
pass `nullptr` for the three result arrays during the search.

Is that enough for your original use case (if you can remember it...)?
