### ISSUE TITLE
Missing error handling on allocation failure

### ISSUE THREAD

**Issue by rafzi** [recastnavigation/recastnavigation#100]
In RecastRasterization.cpp the function addSpan does not handle the case when allocSpan returns nullptr. It does so when no memory rcAlloc fails.

This results in a crash on the following line in addSpan.

The addSpan function should probably have a return value to signal allocation failure to callers.

**Comment by rafzi** [comment]
I would offer to send a pull request for the core code, but it's not really possible to fix the problem for users that are not notified about this change, because they will need to check the return value of a function that previously did not return a value.

Affected APIs would be:

rcAddSpan
rcAddSpans
rcRasterizeTriangle
rcRasterizeTriangles (3 overloads)

They all have a "ctx" parameter for error reporting though, so it would only affect the return value change from void to bool.

**Comment by memononen** [comment]
Hi,

I think it is ok to add return bool value and add an error message on those
functions to indicate that they have failed. It should not break any
current code, but allows people to catch it if needed.

--mikko

**Comment by hymerman** [comment]
@rafzi Did #102 complete everything you wanted to do with this? Are we ok to close this issue?

**Comment by rafzi** [comment]
Yes, this is done.

**Comment by hymerman** [comment]
Great - thanks!
