### ISSUE TITLE
Raycast: What is different with unity3d.Raycast?

### ISSUE THREAD

**Issue by ledouyouxi** [recastnavigation/recastnavigation#104]
http://docs.unity3d.com/ScriptReference/Physics.Raycast.html

Or what way to do it?

From the air raycast and calculate the impact points on the surface?

**Comment by memononen** [comment]
Recast raycast checks "walkability" along the navmesh. You will need a starting point on the navmesh for that. To raycast against level geometry, you should use some other system, i.e. physics or roll your own.
