### ISSUE TITLE
ios crash use recastnavigation

### ISSUE THREAD

**Issue by quaerere** [recastnavigation/recastnavigation#112]
I try to use recastnavigation in IOS devices
 When while accessing const void method() const will crash
But andorid and windows will not appear.

**Comment by hymerman** [comment]
Hi, @quaerere, do you have any more information? A crashdump, callstack or even just a function name would help. Without that information it's not possible to fix I'm afraid!

**Comment by quaerere** [comment]
Hi
  I found this problem. I use unity, but unity also uses reacstnavigation
 When the static linking symbol conflict  So crash
 I use the namespace, which solves this problem.
  
 ------------------ 原始邮件 ------------------
  发件人: "Ben Hymers";<notifications@github.com>;
 发送时间: 2015年12月7日(星期一) 晚上9:45
 收件人: "recastnavigation/recastnavigation"<recastnavigation@noreply.github.com>; 
 抄送: "quaerere"<444536171@qq.com>; 
 主题: Re: [recastnavigation] ios crash use recastnavigation (#112)

 

 
Hi, @quaerere, do you have any more information? A crashdump, callstack or even just a function name would help. Without that information it's not possible to fix I'm afraid!

**Comment by hymerman** [comment]
Excellent - thanks! I'll close this issue now.
