### ISSUE TITLE
Spherical navmesh

### ISSUE THREAD

**Issue by alabd14313** [recastnavigation/recastnavigation#115]
Hi!
Has recast/detour this feature for generating planet navmesh for implementing in blender game engine. blenderartis forum members said No!
They suggest node pathfinding as a solution.
But spherical navmesh can solve some challenges.

**Comment by memononen** [comment]
Blenderartist forum is correct. Recast assumes that there is one up
direction across the whole world.

**Comment by KnIfER** [comment]
It's not easy to change the gravity direction, but maybe we can rotate the mesh verts and generate nav mesh there and then rotate the nav mesh back ?
