### ISSUE TITLE
Determining off mesh directionality 

### ISSUE THREAD

**Issue by jswigart** [recastnavigation/recastnavigation#116]
In dtNavMeshQuery where it determines the right and left poly type I want to determine the directionality of the off mesh link if it's big directional so that I can handle it differently in my custom off mesh code. The problem is that there doesn't appear to be a good way to determine directionality within this function. 

I tried to copy the mechanism that dtNavMesh::getOffMeshConnectionEndPoint uses, but it's not working consistently.

**Comment by jswigart** [comment]
Also I wonder if getOffMeshConnectionEndPoint is robustly implemented. What if there are multiple links from a given poly? How does the loop through the link list know it's looking at the right one?

**Comment by memononen** [comment]
So, you are trying to figure out on which endpoint you entered a link? You
can determine that based on previous polygon and the links. Starting of an
off-mesh link (polyref), and looping through the links the "edge" of the
links tells which end point is connected. Something like this:

dtStatus getEntryIndex(dtPolyRef prevRef, dtPolyRef polyRef, int* index)
{
const dtMeshTile* tile = 0;
const dtPoly* poly = 0;
if (dtStatusFailed(m_nav->getTileAndPolyByRef(polyRef, &tile, &poly)))
return DT_FAILURE | DT_INVALID_PARAM;
for (unsigned int i = poly->firstLink; i != DT_NULL_LINK; i =
tile->links[i].next)
{
if (tile->links[i].ref == prefRef)
{
*index = tile->links[i].edge;
return DT_SUCCESS;
}
}
return DT_FAILURE;
}

where prevRef is the previous poly on path, and polyRef is the ref to the
off-mesh link.

The Off-Mesh Link is a polygon itself, so there is no ambiguity on that
one. You can use getOffMeshConnectionByRef() to get more information about
the off-mesh link.


--mikko

**Comment by jswigart** [comment]
I think the issue I'm having is what to use as prevRef within the scope of the findStraightPath function. path[i] doesn't always work

**Comment by jswigart** [comment]
Btw the location I'm trying to add this functionality is at the 2 spots within findStraightPath that set the flags to DT_STRAIGHTPATH_OFFMESH_CONNECTION

**Comment by memononen** [comment]
path[leftIndex-1] should do it.

--mikko

**Comment by jswigart** [comment]
That never succeeds in getEntryIndex . I tried leftindex - 1, and apexindex since that uses the left or right index depending on the left of right code branch within that loop. Neither got any hits in getEntryIndex. So far the best I've tried is path[i-1] which returns success quite a bit but also fails some too. That been the closest in terms of observation of my guy traversing the link so far. I'm concerned that those failures still point to something not entirely correct about that.

**Comment by jswigart** [comment]
Judging by the call to getPortalPoints that uses path[I] and path[I+1], it appears that the 'prevRef' should probably be path[I].

When I try that I get a good number of successes in the getEntryIndex  function, but when it fails, it appears to fail because prevRef and polyRef are the same value.

Do I need to do this directionality outside the scope of the x == DT_POLYTYPE_OFFMESH_CONNECTION conditional so that it happens even after the first conditional before the block that handles else if (rightPolyType == DT_POLYTYPE_OFFMESH_CONNECTION)

Or perhaps there is a simplification that can be made to this function so that when an off mesh connection is hit, it can be handled before these string pulling area checks and such, since off mesh connections I would imagine should basically get string pulled to a point.

Maybe something like
if ( toType == DT_POLYTYPE_OFFMESH_CONNECTION ) before the 2 blocks that string pull the left and right sides. Perhaps that would make the previous poly more consistent, since it's not relying on state from previous iterations of the loop as it does inside the scope that currently checks for the off mesh 
else if (leftPolyType == DT_POLYTYPE_OFFMESH_CONNECTION)
and 
else if (rightPolyType == DT_POLYTYPE_OFFMESH_CONNECTION)

**Comment by jswigart** [comment]
As an aside, what are your thoughts about adding a value to the dtPolyTypes flags, to use one of those available bits to mark a poly as reversed? (assuming each direction of a bidirectional connection gets its own poly). Then you'd have all the directional context you need from the offmesh poly by itself and not have to mess with the previous area in cases like this.

**Comment by memononen** [comment]
Using i is not correct in this case. The i is the current polygon, and one
of left or right is further back. One option is to calculate the value when
getting portal, and store it in the same way as leftFlags/rightFlags.

--mikko

**Comment by jswigart** [comment]
This appears to work consistently

dtPolyRef prevRef = path[apexIndex];

where apexIndex is the leftIndex or rightIndex depending on which of those 2 blocks it's in.

Basically the same as your original suggestion without the -1
