### ISSUE TITLE
DetourObstacleAvoidance.cpp：531   unused variable 'nd2'

### ISSUE THREAD

**Issue by kbengine** [recastnavigation/recastnavigation#124]
DetourObstacleAvoidance.cpp：531   unused variable 'nd2'

**Comment by kbengine** [comment]
RecastMesh.cpp:382:4: error: multi-line comment
//   / |C   D|  \
^

**Comment by kbengine** [comment]
gcc 5.2.1 ubuntu

**Comment by grahamboree** [comment]
Fix for this is currently in PR #76
