### ISSUE TITLE
Issue tagging

### ISSUE THREAD

**Issue by hymerman** [recastnavigation/recastnavigation#128]
I noticed @grahamboree started tagging some issues as bugs - which is cool because it's something I was going to suggest! Should we pick a nice common set of tags to standardise on?

There are loads of articles about issue tagging best practices:

* http://programmers.stackexchange.com/questions/129714/how-to-manage-github-issues-for-priority-etc
* https://docs.saltstack.com/en/latest/topics/development/labels.html
* https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/

I don't think we need to go quite as far as they do (I don't think functional areas or the milestones feature are useful for us, for example) but it would be nice to have some of it. At least category (bug/feature/discussion etc), and perhaps a status (resolved/wontfix etc). Thoughts?

**Comment by grahamboree** [comment]
I think the real benefit of labels is just being able to see quickly what the status of everything is at a high level.  At work, we have a pretty extensive issue labeling system that works well for us (labeling sprints, components, severity, etc..) but we also have an order of magnitude more issues than recast does. :stuck_out_tongue: I'd say, let's stick with something lightweight for now until we find the need to get more fine-grained to stay organized.  I like the Robin article's list, specifically how similar concerns are color-coordinated, though I think about 1/3 of those tags are relevant to us.  Want to just go with the relevant labels from their list for now?

**Comment by Kromster80** [comment]
I like the Programmers categorization better for it has type in each of its items - something that helps a lot to keep an eye on. It's clear and can be colored just as well by category.

**Comment by grahamboree** [comment]
I've added a few labels from the robin link that seem immediately relevant.  I think we should follow that style (color coding categories of labels) in the future, but we probably don't need to get much more crazy with labeling right now.  Here's my take on their definitions:

label | meaning
------ | -----------
bug | undesired behavior, crashes, memory leaks, etc..
duplicate | this issue has already been reported
enhancement | change that would make an existing feature better
feature | a new feature/function that would be useful to have
invalid | this is not an appropriate or meaningful discussion to have here
optimization | performance-oriented issues or proposals
question | general discussion
wontfix | this is desired behavior and not something we're going to change.

I'm going to close this issue for now.  If we feel we need anything more than this in the future, we can re-open it.

**Comment by hymerman** [comment]
Thanks Graham; I just realised I opened this then went away for 5 days - sorry! I agree, that cut-down list looks good. I've just added 'documentation' too which the robin link doesn't mention, but I think is useful.

**Comment by grahamboree** [comment]
Awesome.  Documentation is another good one.  :smile:
