### ISSUE TITLE
Upgrade to SDL 2.0

### ISSUE THREAD

**Issue by grahamboree** [recastnavigation/recastnavigation#135]
There's currently issues in SDL 1.2 preventing it from linking with RecastDemo when using Visual Studio 2015.  Given this, it's probably time to upgrade to 2.0.  There shouldn't be a whole lot of issues in the process, as RecastDemo mostly just relies on it for input events and creating a window with a gl context.

**Comment by Janiels** [comment]
Last I saw @rwindegger uses SDL 2 over in his fork. Though it's probably too diverged to be easily integrated.
