### ISSUE TITLE
Discuss versioning, and release a 'first new version'

### ISSUE THREAD

**Issue by hymerman** [recastnavigation/recastnavigation#162]
We've mentioned in other issues that we should make use of Semantic Versioning (http://semver.org/spec/v2.0.0.html) before we start accepting breaking changes.

I imagine that along with that, we'll also want to start using git tags, GitHub releases, GitHub milestones, generate release descriptions, and perhaps use Travis and AppVeyor to upload built libraries to GitHub releases. And of course... we'll want to actually make our first release.

I propose we follow Semantic Versioning (MAJOR.MINOR.PATCH), starting at 1.5.0 (since the last labelled release was 1.4: https://code.google.com/p/recastnavigation/downloads/list?can=1&q=), tagging new releases when we are in agreement with the version number as it is (no leading 'v' as GitHub suggests). We should create 1.5.0 as soon as we're agreed on how we'll handle versioning - no sense waiting around for some arbitrary set of bugs to be fixed :)

I suggest we create a GitHub milestone for each new version (and for the next version), and label issues and PRs with them. That way we can keep track of when we can merge breaking PRs, without using lots of confusing per-release branches. Some people swear by git-flow but I'm not so sure myself - I think we can get by with just a 'master' branch.

There are projects that can generate release notes automatically but frankly that might be a bit more hassle than it's worth - I suggest we just write release notes ourselves, highlighting the most important changes and providing a link to the list of issues tagged with that release's milestone if users want more detail.

It's also possible to upload binaries with each release, and to do this automatically on new tags from Travis and AppVeyor, but I'm not totally sure of the value of that - personally I would always prefer to download source. If someone else thinks this is worth doing, we can look into it, otherwise let's just leave releases as "git tags with a nice description on GitHub".

Thoughts?

**Comment by Janiels** [comment]
That sounds good to me. I particularly agree that we don't need built libraries - including the parts of R&D you need in your own source tree is probably easier since it is pretty well structured, and you still would need headers regardless.

The only case of prebuilt binaries I can think of would be the demo. I don't know if we want to include that in the labelled releases though? It could certainly be useful in various scenarios to demonstrate how R&D has evolved or look at new features you would get by upgrading. However, it is probably a headache to build binaries for (at least) the 3 major platforms. So I think it would be fine to leave them out.

I'm not very familiar with how GitHub releases work - I assume it will be a source dump of the repo if it's powered by tags?

Also agree about milestones and the simple branching model which we are already using.

**Comment by hymerman** [comment]
Good points about RecastDemo; I also think it will be fine to leave it out.

GitHub releases get created semi-automatically whenever you push tags - see my fork of wall-t for example; there are 4 pushed tags:

https://github.com/hymerman/wall-t/tags

And GitHub creates a release for each of them automatically, 2 of which I have clicked the 'make this a proper release' button to add a description and optional downloads. It also makes them much more prominent than the other tags, with big buttons and different styling:

https://github.com/hymerman/wall-t/releases

I added the built zip myself, but the source downloads are generated by GitHub. The source downloads are still provided for the other tags.

**Comment by Janiels** [comment]
I see, that looks good then. How should we do the tagging? If we were to follow the semantic versioning rules to the dot it seems we would have to do it on almost every merged PR to master. Perhaps we could set up a better chat where we could discuss when to tag. Something like [Gitter](https://gitter.im/) maybe?

**Comment by hymerman** [comment]
I believe the semantic versioning applies to released versions only, rather than every commit that makes it into the repository, so we can choose when we make a release and apply the version numbering rules at that point. I guess gitter would be a good place to discuss when to release - I've just set it up here: https://gitter.im/recastnavigation . We can give it a go!

**Comment by Janiels** [comment]
That makes way better sense. :-)

**Comment by hymerman** [comment]
@grahamboree What's your take on this? Once we're in agreement I'll get on it.

**Comment by grahamboree** [comment]
I agree with everything that's been said.  I think just calling the latest on master 1.5.0 is a good first step.  Going forward though, we may have PR's that need to wait for the next major release, while other bugfixes might be able to be merged immediately.  Should we leave the major change PR's open until we're working towards a next major?  I think it's only a problem if there's code in a PR for a major hanging around that someone wants to build off of.  

I'm not sure what a great solution for this is, or how much of a problem this will be.  On one hand it's nice to just have a master branch.  On the other, git flow was more or less designed to solve these problems, but it requires much more work and diligence to maintain.  I think for now I'm in favor of sticking with what we have until it becomes a more important problem.

**Comment by leif81** [comment]
I'm a fan of semver and a less is more approach to branching. I find gitflow too heavy so I typically use use a lighter weight version that goes something like this:

Once the `1.5.0` gets tagged on `master`, then `master` reopens for merging PR's that are planned for the `1.6.0` milestone. If a critical bug is found in the `1.5.0` release, create a branch (e.g. call it `release-1.5`) from the `1.5.0` tag, put the fix on this new branch, tag the new `1.5.1` release, and merge it back into `master`. It looks something like this:

    -------(1.5.0)-------------------------------------(1.6.0)----------> [master]
              \                                           \  
               ---(1.5.1)---(1.5.2)---> [release-1.5]        ---(1.6.1)---(1.6.2)---> [release-1.6]

**Comment by hymerman** [comment]
@leif81, I really like the look of this approach. How do you deal with breaking changes that would come as part of 2.0.0 in your example? Is there another branch gathering those commits?

I'll tag 1.5.0 now and we'll deal with the rest soon!

I think we should aim to integrate as many backwards-compatible PRs and fix as many issues as we can to get out a 1.6.0 next, then have a good think about what breaking changes we want to make and work towards bundling them all together into a 2.0.0.

**Comment by hymerman** [comment]
Released:

https://github.com/recastnavigation/recastnavigation/releases/tag/1.5.0

I'll close this issue once we've decided what to do with branches for new versions.

**Comment by leif81** [comment]
@hymerman Hmm I think first what I'd discourage folks from working on issues assigned to milestones that are too far in the future to avoid any nasty conflicts. But if someone is eager and a PR comes in I'd personally just leave it unmerged until the that milestone becomes the active one on `master`.

**Comment by Janiels** [comment]
I believe this can be closed, right?

**Comment by hymerman** [comment]
Sorry, forgot about this one! I was going to have a think about branching.

What we'll do is similar to what @leif81 suggested - encourage users to make their changes backwards-compatible, but save up incompatible changes, in issues and pull requests labelled as being for the next major milestone.

Inevitably maintaining backwards-compatibility will lead to features being done not quite as intended, so we can also make issues to tweak them for the next major release.

As for branching, we'll keep it simple (again exactly as per @leif81's suggestion - thanks!) and create a 'release-1.5' branch when we want to release a patch version (and maybe later a 'release-1' branch if needed?), which contains changes cherry-picked from master and tagged on releasing patch versions. Aside from that, all development will be done in master.

If we do find that too many changes are accumulating for the next major release, we could create a branch for it and merge them in, but I imagine it'll remain fairly stable... let's just be sensible about it and see what happens!

I'll close this now.

**Comment by grahamboree** [comment]
Great!  I think that's a smart approach. We do something similar at work and it's served us well. 👍
