### ISSUE TITLE
Enable C++11/14 for RecastDemo in Travis/Appveyor

### ISSUE THREAD

**Issue by grahamboree** [recastnavigation/recastnavigation#163]
Stemmed from discussions on #160

Apparently this is difficult with Travis' ancient setup.
http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

We'll also need to determine which Appveyor environments we can use as well.  We're currently compiling back to VS2010, which has a weird half-implementation of C++11.  I think this will really come down to "lets build VS2010 until we can't."

The rationale for using 11/14 is that they give us performance and code clarity gains out of the box.  These come with the drawbacks that they only work on platforms with modern compilers.  Where RecastDemo is mainly going to run on Windows, OSX, or Linux, this is not an issue, and we should be fully taking advantage of new C++ features where it makes sense.

This however, is not the case for Recast and Detour itself.  We're not 100% certain that modern game platforms are running with modern compilers, so we really have to assume they're not.  Things definitely are moving in the right direction in the industry, but I can't speak for every user of Recast having access to a modern C++ toolchain.

**Comment by jackpoz** [comment]
It might be useful to set up a build matrix for travis, one with -std=c++98 that would build only Recast and Detour and another one with latest C++11/14 features building RecastDemo too.
This will allow to take advantage of latest C++ improvements in RecastDemo while being notified if some C++11 code slips into R&D.

**Comment by hymerman** [comment]
I've decided I strongly dislike Travis. They just really don't care about C++. I may look into getting our own build machine on Azure or something...

**Comment by jackpoz** [comment]
got any particular issue ? I use travis for https://travis-ci.org/TrinityCore/TrinityCore and it works very good after the initial painful apt-get setup (installing up-to-date tools that support C++11 and such).
I'd like to help if you need to set it up

**Comment by hymerman** [comment]
I was trying to get clang 3.8 and GCC 5 working, but Travis' environment is just so out of date... I've been having a nightmare in this branch: https://github.com/hymerman/recastnavigation/tree/cpp11

Last time I tried, Travis had clang 3.4 which failed for weird reasons (found an example build: https://travis-ci.org/hymerman/recastnavigation/jobs/97120714). I see TrinityCore is using clang 3.5 on Travis - that's still quite old but maybe it'll work for us (it is C++14 complete)... GCC is just stuck at 4.8 forever it seems.

The objective here is to get the core libraries building with C++03 and C++11/14, and to build the demo under C++11/14. Looks like we can accomplish this with a build matrix using GCC 4.8 for just the core libraries, and clang 3.5 for everything in C++14 mode. I'll give that a try next :)

I'm still annoyed with Travis though - we've spent a lot of time trying to get it to do what we want, it would be way easier to do if we were just hosting CI ourselves! Ugh.

(thanks jackpoz, btw :) )

**Comment by jackpoz** [comment]
After changing the Ubuntu distro to 14.04 (which I see you did already) installing an updated compiler version comes down to "Install gcc X on Ubuntu 14.04" (which I know is still going to be painful to setup with travis, speaking for experience).

If it can help I'll link what we used for a while to add new repos https://github.com/TrinityCore/TrinityCore/blob/a6f6bb4fccb6c0a5123ef7fd553cf12b6a31db1f/.travis.yml#L12 , useful when the current repos don't have the tool versions required.

Build matrix let you define env variables that you can use to execute different apt-get commands depending on which job you are running at the moment. The resulting .travis.yml will look ugly and unreadable but that seems to be a common thing among all *.yml files :) Maybe start with 1 single job, that's still going to require enough effort to get it to work.

TrinityCore is using clang 3.5 as lowest supported compiler on purpose, it was also a requirement to keep using travis when llvm.org disabled their apt-get repo for a few days last June(which ofc broke all our builds)

**Comment by grahamboree** [comment]
I've come around on this over the years and don't think it's a terribly useful change.  While C++ > 03 will come with some conveniences in RecastDemo, the current code is working and the overhead of keeping the demo and library code separate and consistent is probably not worth the benefits we'd get from allowing newer C++ versions.
