### ISSUE TITLE
getHeight() returning RC_UNSET_HEIGHT

### ISSUE THREAD

**Issue by wbierman** [recastnavigation/recastnavigation#168]
Hello.  I'm not entirely sure what causes it, but getHeight() in RecastMeshDetail.cpp will return RC_UNSET_HEIGHT in the case that all checked neighbors also have an unset height.  This was giving me some mesh triangles that reached up to cellHeight*65535, which doesn't seem like the correct behavior.

I added this at the end of the if statement within that function, and it seemed to help:

```
        if (h == RC_UNSET_HEIGHT)
            h = static_cast<unsigned short>(fy / ch);
```

The idea is that if we cannot determine a height, we can use the input value as a guess.

Thoughts?

**Comment by Janiels** [comment]
Is this happening with the changes in #154?

**Comment by wbierman** [comment]
No.  I am on revision 6285b17587bf06d2d71a32df74e22e1d18da93fc.  I can update and try again if you think it would help?
