### ISSUE TITLE
Coverity scan

### ISSUE THREAD

**Issue by hymerman** [recastnavigation/recastnavigation#173]
We should set up a branch to point Coverity Scan at, for another source of static analysis.

I signed us up already thinking I could get it all done in 5 minutes but it turns out it's not quite as trivial as I thought. I'll leave this issue here to let everyone know it's being thought about at least!

https://scan.coverity.com/projects/recastnavigation-recastnavigation

**Comment by jackpoz** [comment]
Here are the scripts I use on Ubuntu x64 in case you might need them:

covupdate.sh used to download latest Coverity Scan version and configure it for gcc. You can find the correct wget command clicking on "Submit Build" on coverity
```sh
wget https://scan.coverity.com/download/linux-64 --post-data "token=<your secret project token>&project=<Your Project Name>" -O coverity_tool.tgz
tar -zxvf coverity_tool.tgz
rm -f -r cov-analysis
mv cov-analysis-linux64-* cov-analysis
rm -f -r coverity_tool.tgz
cd cov-analysis
cd bin
./cov-configure --gcc
```


cov.sh used to build the project (recast in your case) with Coverity Scan tool creating the data for analysis. it has to be executed in the folder with project files. It will create a subfolder "cov-int" with everything needed by coverity and zip it for the upload.
```sh
make clean
/home/user/cov-analysis/bin/cov-build --dir cov-int make -k
/home/user/cov-analysis/bin/cov-import-scm --dir cov-int --scm git --log cov-int/scm_log.txt 2>&1
tar czvf tc.tgz cov-int
```


covup.sh used to upload the analysis data. You can find the correct curl command clicking on "Submit Build" on coverity
```sh
curl --form project=<project name> --form token=<secret token> --form email=<email>  --form file=@tc.tgz --form version=none --form description=none https://scan.coverity.com/builds?project=<project name>
```

**Comment by hymerman** [comment]
Fantastic, thanks @jackpoz!

**Comment by hymerman** [comment]
I've done a build and uploaded to Coverity Scan - there are some good issues reported! This is definitely a useful service.

I'll have a look at automating this through Travis and setting up a `coverity_scan` branch so as not to run it all the time, as Coverity recommends.

**Comment by kklouzal** [comment]
I browsed through your build history on TravisCI, the frequency in which they run is well within the bounds of how many times you can allow CoverityScan to run. I suggest having it automate the main branch and sticking the Coverity badge in the readme as this is a place many developers go to start improving projects. It's easy to forget pushing to the coverity_scan branch and I was sad to see the project hasn't been scanned in almost a year!

**Comment by psi29a** [comment]
We can setup a github cron job that does this automatically. I can either help walk someone through it or do it myself if I had access. OpenMW makes extensive use of Recast and have found some issues in it (by accident) that we now exclude along with other libraries. 

Our idea was to just fork the libraries we use on our github repo, run the cronjobs there on https://github.com/OpenMW in our own Coverity account then share the reports here in issues and possibly send PRs as well. If we can cut out the middle-man (us) then that would be better. :)

**Comment by grahamboree** [comment]
Migrated to #642 to revive or replace automatic coverity scanning.
