### ISSUE TITLE
Crash in RecastDemo, x64, VS2015

### ISSUE THREAD

**Issue by b-desconocido** [recastnavigation/recastnavigation#185]
File: Filelist.cpp
Function: scanDirectoryAppend
Line: 38
`long fh = _findfirst(pathWithExt.c_str(), &dir);`
According to [MSDN](https://msdn.microsoft.com/ru-ru/library/zyzxfzac.aspx) fh should be 'intptr_t':
`intptr_t fh = _findfirst(pathWithExt.c_str(), &dir);`
With this fix i'm able to "Choose mesh" without a crash. Sorry for my bad English ;-)

**Comment by hymerman** [comment]
Thanks @b-desconocido - I've just submitted a PR to fix this.
