### ISSUE TITLE
No guard on dtCrowd::getAgent

### ISSUE THREAD

**Issue by JimmyJames707** [recastnavigation/recastnavigation#19]
getAgent doesn't have a guard on it, while the other functions that address agents do.

const dtCrowdAgent* dtCrowd::getAgent(const int idx)
{
    return &m_agents[idx];
}

void dtCrowd::updateAgentParameters(const int idx, const dtCrowdAgentParams* params)
{
    if (idx < 0 || idx >= m_maxAgents)
        return;
    memcpy(&m_agents[idx].params, params, sizeof(dtCrowdAgentParams));
}

**Comment by Janiels** [comment]
This has already been fixed.
