### ISSUE TITLE
Are OffMeshLinks Limited to Tile Neighbours?

### ISSUE THREAD

**Issue by graehu** [recastnavigation/recastnavigation#195]
After having a read through of dtNavMesh::addTile() it looks like it's not possible to connect to tiles that aren't [neighbours][1]. If that is the case, what would the best way to implement a teleporter be?

[1]:https://github.com/recastnavigation/recastnavigation/blob/master/Detour/Source/DetourNavMesh.cpp#L967

**Comment by Janiels** [comment]
Yes, off mesh connections are only supported within tiles and to adjacent tiles. The best way to implement a teleporter would probably be to fix this, or to use some hierarchical path planning on top of Detour.

One possible solution would be to expand the code in `addTile` to connect off mesh links to/from all other tiles in the mesh, although this might be a bit slow but maybe it's acceptable for your use case.
Another solution is to fully implement dynamic links. #129 is kind of related - @memononen mentions using a pool for links, which could support dynamic off mesh connections, including connections farther than just an adjacent tile.

Supporting dynamic links and by extension non-adjacent off mesh connections is a feature we definitely want to have at some point, but haven't gotten around to implementing. PR's are always welcome!

**Comment by graehu** [comment]
Thanks for getting back to me. I'm using detour through UnrealEngine 4, so any changes you make wouldn't make it in for quite some time probably. For now, I'm going to increase my tile size to accommodate for the distance of teleporters in each of my levels. Thankfully they're quite small.

Though, if I think about changing how links in my version of UE4 work I'll let you know. Based on the link exit coordinates I think it could be relatively trivial to find the exit tile rather than simply checking neighbours. But maintaining state whenever that tile is modified may be less trivial, my understanding of Detour isn't good enough to fully gauge the problem at this point sadly. :P

I'll keep an eye out for cool changes to Detour either way though because it's awesome!

**Comment by Janiels** [comment]
Detour only stores off mesh connection in the starting tile. This means that if you have an off mesh connection pointing from tile A to B and you have loaded tile A first it will not be able to connect the off mesh connection when tile B is loaded. This can potentially give you some inconsistent results depending on the tile load order, should you choose to go with the "find exit tile" solution.
A potential fix to that problem could be to store off mesh connections in both tiles.
