### ISSUE TITLE
gcc error: no newline at end of file

### ISSUE THREAD

**Issue by kbengine** [recastnavigation/recastnavigation#198]
gcc error: no newline at end of file

DetourCrowd.h
DetourNavMeshBuilder.h

**Comment by grahamboree** [comment]
Thanks.  Mind submitting a PR?

**Comment by jackpoz** [comment]
Travis build worked fine using GCC https://travis-ci.org/recastnavigation/recastnavigation/jobs/119295066 , isn't that you are confusing a GCC warning with an error ?

**Comment by grahamboree** [comment]
AFAIK this was *technically* a C++ standard requirement up until C++11, but most compilers were pretty lax about it. I could imagine that older versions of GCC would complain in a warning or something, and if you were running warnings as errors, it'd be annoying.  Given that more effort has been spent talking about this than hitting the enter key a few times, I'm going to go ahead and do this myself.
