### ISSUE TITLE
License of models

### ISSUE THREAD

**Issue by phlogios** [recastnavigation/recastnavigation#210]
I'm writing a research paper and would like to use the models included in the RecastDemo folder for performance comparisons. Is this allowed in their license? I can't find a license for the models specifically, and I don't want to assume that the license is zlib just because Recast itself is licensed under zlib.

**Comment by grahamboree** [comment]
Good question.  I vaguely remember @memononen saying he grabbed them from a colleague of his who released them under a fairly liberal license with the intent that they be used for prototyping.  Where they don't have an individual license I think it's safe to assume they're under zlib, though I think only @memononen could answer this for sure.

There are also some pretty good obj's [here](http://graphics.cs.williams.edu/data/meshes.xml) that I've used for profiling changes to Recast.

**Comment by Janiels** [comment]
Here is the comment @grahamboree is (probably) referring to: https://github.com/recastnavigation/recastnavigation/issues/155#issuecomment-174503422
