### ISSUE TITLE
Which version of recastnavigation is used in UE4?

### ISSUE THREAD

**Issue by ledouyouxi** [recastnavigation/recastnavigation#220]

**Comment by Janiels** [comment]
I believe it is based on R&D 1.4 with several modifications:
https://github.com/masagroup/recastdetour
I seem to remember that UE is using this one. It looks like it has diverged significantly from this repo.
It may be a better idea to ask the UE guys if you want to be completely sure.

**Comment by ledouyouxi** [comment]
thanks!
