### ISSUE TITLE
when test obstacle demo, a big radius agent can find path through little gap between two obstacle.

### ISSUE THREAD

**Issue by chendezhao** [recastnavigation/recastnavigation#226]
when test obstacle demo, a big radius agent can find path through little gap between two obstacle.
it looks strange. Can i set path radius to advoid this condition?
![gothroughlittlecrack](https://cloud.githubusercontent.com/assets/9063833/17923245/c1b0512a-6a15-11e6-8817-60136a77d9db.png)

**Comment by hymerman** [comment]
The obstacles aren't eroding the navmesh enough - see how the static geometry has a border around it - the obstacles need this too. I forget what the obstacle API looks like now but you need to either tell them to erode by the agent radius (if that's an option), or instead add the obstacles with the agent radius added to their own (so they look bigger than they actually are). Does that make sense?

**Comment by chendezhao** [comment]
@hymerman  thanks for your answerser,  i think it is workable. But, in a game i have many types agent with different radius, like a person, a car , a tank, Does it mean, i need recalculate obstacles' radius when different agent pathfind?

**Comment by hymerman** [comment]
Ah, in that case you're already in tricky territory! The navmesh around static geometry is generated with a specific agent radius, so the navmesh technically only supports agents with that radius. What we recommend is to generate a different navmesh for each agent size (and so each obstacle you add would be added into each navmesh with a different size).

Note though that Detour Crowd doesn't support this - the agents on different navmeshes won't avoid each other without some extra work.

**Comment by chendezhao** [comment]
think you, very much
