### ISSUE TITLE
Recurring System.AccessViolationException

### ISSUE THREAD

**Issue by TheNoobCompany** [recastnavigation/recastnavigation#229]
I'm having an issue with this function: rcVsub(Single* dest, Single* v1, Single* v2) dans 

Wether I'm 100% ram or just < 30%, it will sometimes throw a System.AccessViolationException, and it will always be inside this specific function.

Also, on a specific tile generation, I'm able to reproduce this issue 100% of the time, even if I just rebooot my PC and my RAM is empty.

v1/v2 unable to read memory

sometimes only v1, sometimes only v2, sometimes both.

Any idea ?

  
```
 à rcVsub(Single* dest, Single* v1, Single* v2) dans e:\développement\thenoobbot\thenoobbot\meshreader\recastlayer\recast\recast.h:ligne 649
   à ?A0xc7c409e5.calcTriNormal(Single* v0, Single* v1, Single* v2, Single* norm) dans e:\développement\thenoobbot\thenoobbot\meshreader\recastlayer\recast\recast.cpp:ligne 235
   à rcClearUnwalkableTriangles(rcContext* ctx, Single walkableSlopeAngle, Single* verts, Int32 nv, Int32* tris, Int32 nt, Byte* areas) dans e:\développement\thenoobbot\thenoobbot\meshreader\recastlayer\recast\recast.cpp:ligne 293
   à RecastLayer.RecastContext.ClearUnwalkableTriangles(Single walkableSlopeAngle, Single[]& vertices, Int32[]& tris, Byte[] areas) dans e:\développement\thenoobbot\thenoobbot\meshreader\recastlayer\recastlayer.cpp:ligne 56
   à meshBuilder.TileBuilder.Build(Int32 i, Int32 j) dans E:\Développement\TheNoobBot\TheNoobBot\meshReader\meshBuilder\TileBuilder.cs:ligne 242
   à meshBuilder.ContinentBuilder.Build() dans E:\Développement\TheNoobBot\TheNoobBot\meshReader\meshBuilder\ContinentBuilder.cs:ligne 257
   à meshBuilderGui.Interface.RunBuild() dans E:\Développement\TheNoobBot\TheNoobBot\meshReader\meshBuilderGui\Interface.cs:ligne 154
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Janiels** [comment]
It is unlikely this is an error in Recast - it is much more likely it is an error in your own code (probably your .NET wrapper).
`rcClearUnwalkableTriangles` is passed a few pointers - make sure those point to correct memory, and that the lengths you are passing are correct.

**Comment by TheNoobCompany** [comment]
c# call : Context.ClearUnwalkableTriangles(Config.WalkableSlopeAngle, ref vertices, ref triangles, areas);

for  void ClearUnwalkableTriangles(float walkableSlopeAngle, array<float>^% vertices, array<int>^% tris, array<unsigned char>^ areas);


What could be wrong, I just use a "ref" from C#

`		void RecastContext::ClearUnwalkableTriangles(float walkableSlopeAngle, array<float>^% vertices, array<int>^% tris, array<unsigned char>^ areas)
		{
			pin_ptr<float> verticesPointer = &vertices[0];
			pin_ptr<int> trisPointer = &tris[0];
			pin_ptr<unsigned char> areasPointer = &areas[0];
			rcClearUnwalkableTriangles(_context, walkableSlopeAngle, verticesPointer, vertices->Length / 3, trisPointer, tris->Length / 3, areasPointer);
		}`


`void rcClearUnwalkableTriangles(rcContext* ctx, const float walkableSlopeAngle,
								const float* verts, int /*nv*/,
								const int* tris, int nt,
								unsigned char* areas)
{
	rcIgnoreUnused(ctx);
	
	const float walkableThr = cosf(walkableSlopeAngle/180.0f*RC_PI);
	
	float norm[3];
	
	for (int i = 0; i < nt; ++i)
	{
		const int* tri = &tris[i*3];
		calcTriNormal(&verts[tri[0]*3], &verts[tri[1]*3], &verts[tri[2]*3], norm);
		// Check if the face is walkable.
		if (norm[1] <= walkableThr)
			areas[i] = RC_NULL_AREA;
	}
}`

**Comment by TheNoobCompany** [comment]
Dumped lenght from C# code right before the exception happend:

verticles.Lenght: 13488786
triangles.Lenght: 8440425
areas.Lenght: 2813475

**Comment by TheNoobCompany** [comment]
Can it simply be because C# app cannot take over 2GB of ram ?
When it crash, the total RAM is  1 871 192K

**Comment by JeanPierreC** [comment]
Correct me if I'm wrong, but I believe recast is a 32-bit.  Meaning 32-bit memory addressing.  Can you check to see if the process grows to larger than 2 gigs and memory consumption? (https://en.wikipedia.org/wiki/2_GB_limit)

**Comment by JeanPierreC** [comment]
Exactly right.

**Comment by TheNoobCompany** [comment]
1871192K, I suppose we are talking about Kibibytes here and not kilobytes ?

It would be approx 1.9GB, I guess, if you add the memory that got lost during the crash, it would be 2GB limit.

Recast is 32bits, yes, but even, C# limit 64bits app to 2GB anyway, damn ...

I should check for freeing more memory but I don't think I necesserly have memory leak tho.

**Comment by Janiels** [comment]
`rcClearUnwalkableTriangles` is not allocating any memory, so I don't think it is that.

Try adding 3 `GC,KeepAlive` calls for `vertices`, `indices` and `areas`, although you are probably referencing these after the call, so it shouldn't make a difference.
Also try something like:
```float sum = 0;
foreach (int i in triangles)
  sum += vertices[i].X + vertices[i].Y + vertices[i].Z;

Console.WriteLine(sum);
```
after your `GetRawData` call. This will confirm that none of the indices are out of range.

**Comment by TheNoobCompany** [comment]
After the deadly call, there is already memory cleaning:
vertices = null;
triangles = null;
areas = null;
GC.Collect();

But too late .

I'll add the sum code and see the results.

**Comment by Janiels** [comment]
That code means `vertices`, `triangles` and `areas` will have no references while the call is happening. This means that the GC can garbage collect those 3 arrays during the call to `ClearWalkableTriangles`. This would cause the exact problems you are seeing.

You need to add `GC.KeepAlive` for those 3 variables after `ClearUnwalkableTriangles`.

**Comment by TheNoobCompany** [comment]
So it would garbage collect their memory space meanwhile they are used ? 

I'll add that, but isn't it too late as the error happend in the C++ code and not in the c# one ?

**Comment by Janiels** [comment]
The GC has no way of knowing that they are being used because Recast is native code.
`GC.KeepAlive` will just mean the GC cannot collect the arrays until after the 3 `GC.KeepAlive` calls, as they will be used by those 3 calls. This is exactly what you want, and the entire purpose of the `GC.KeepAlive` method.

**Comment by TheNoobCompany** [comment]
this way ?

```                Console.WriteLine("Context.ClearUnwalkableTriangles: verticles: " + vertices.Length + ", triangles: " + triangles.Length + ", areas: " + areas.Length);
                Context.ClearUnwalkableTriangles(Config.WalkableSlopeAngle, ref vertices, ref triangles, areas);
                #if (TIMETHIS)
                    Console.WriteLine("ClearUnwalkableTriangles: " + (stopWatch.ElapsedMilliseconds - cur) + ", total: " + stopWatch.ElapsedMilliseconds);
                    cur = stopWatch.ElapsedMilliseconds;
                #endif
                Context.RasterizeTriangles(ref vertices, ref triangles, ref areas, hf, Config.WalkableClimb);
                #if (TIMETHIS)
                    Console.WriteLine("RasterizeTriangles: " + (stopWatch.ElapsedMilliseconds - cur) + ", total: " + stopWatch.ElapsedMilliseconds);
                    cur = stopWatch.ElapsedMilliseconds;
                #endif

                GC.KeepAlive(vertices);
                GC.KeepAlive(triangles);
                GC.KeepAlive(areas);```

**Comment by TheNoobCompany** [comment]
sum result is: -3,48679E+10 // no index out of range exception

```
            float sum = 0;
            foreach (int i in triangles)
                sum += vertices[i] + vertices[i+1] + vertices[i+2];

            Console.WriteLine(sum);
```

**Comment by Janiels** [comment]
Since they are floats it should be:
```
foreach (int i in triangles)
  sum += vertices[i*3+0] + vertices[i*3+1] + vertices[i*3+2];
```

**Comment by TheNoobCompany** [comment]
Well, with the updated code, it goes -4.42393477E+10

but still no index out of range exception, last test 1.4GB ram, nowhere near 2GB.

**Comment by TheNoobCompany** [comment]
Actually, there is... IndexOutOfRangeException, I didn't see it because I have another "i" in that function, and my foreach uses a "i2", but I copy pasted your code and it contained i, well, w/e....

I'll try and see why I don't have enough vertices for my triangles then...

Are you sure about the "i*3" tho ?

I'll run the test directly on Geometry.Triangles and Geometry.Vertices since it got the real Vector3 class and it will be easier to read with X, Y, Z stuff.

**Comment by Janiels** [comment]
Yeah, it should be `*3` since each index is a reference to a vertex, and each vertex has 3 components.

**Comment by TheNoobCompany** [comment]
Out of range exception with this as well:

```
            float sum = 0;
            foreach (var t in Geometry.Triangles)
            {
                sum += Geometry.Vertices[(int)t.V0].X + Geometry.Vertices[(int)t.V0].Y + Geometry.Vertices[(int)t.V0].Z;
                sum += Geometry.Vertices[(int)t.V1].X + Geometry.Vertices[(int)t.V1].Y + Geometry.Vertices[(int)t.V1].Z;
                sum += Geometry.Vertices[(int)t.V2].X + Geometry.Vertices[(int)t.V2].Y + Geometry.Vertices[(int)t.V2].Z;
            }
            Console.WriteLine(sum);
```

**Comment by TheNoobCompany** [comment]
Thanks for pointing me out to the issue, I found how to resolve my problem.

I had bad file reading leading me to have  shifted data, making the first triangle of each file the max value of a ushort, that's why it was out of bound (no vertex[65536])
