### ISSUE TITLE
out of range by dtNavMeshQuery::findRandomPointAroundCircle

### ISSUE THREAD

**Issue by lupurs** [recastnavigation/recastnavigation#236]
When I use dtNavMeshQuery::findRandomPointAroundCircle, the results sometimes out of the maxRadius.

**Comment by lupurs** [comment]
S_WARN    cellapp01 12000 8001120  [2016-09-22 15:31:38 292] - self.walkTargetPos: Vector3(90.846893, 19.994532, 64.043793), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 13.77803897857666, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:31:48 292] - self.walkTargetPos: Vector3(94.780449, 18.390574, 81.796570), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 20.08432388305664, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:31:57 292] - self.walkTargetPos: Vector3(78.486984, 18.324789, 74.448730), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 4.622967720031738, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:32:04 292] - self.walkTargetPos: Vector3(83.702942, 19.994532, 62.315426), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 9.457490921020508, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:32:11 293] - self.walkTargetPos: Vector3(80.211182, 18.294531, 66.348679), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 3.965822458267212, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:32:18 292] - self.walkTargetPos: Vector3(76.066261, 18.230558, 65.833252), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 4.855213642120361, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:32:25 292] - self.walkTargetPos: Vector3(71.955894, 18.306664, 75.833435), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 8.960700035095215, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:32:32 292] - self.walkTargetPos: Vector3(88.172112, 18.294531, 71.440079), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 9.703731536865234, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:32:39 292] - self.walkTargetPos: Vector3(89.493324, 19.994532, 63.648022), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 12.781473159790039, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:32:47 292] - self.walkTargetPos: Vector3(94.416763, 18.380041, 80.090965), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 18.816608428955078, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:32:55 292] - self.walkTargetPos: Vector3(92.581932, 18.294531, 69.113632), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 14.00244426727295, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:33:02 292] - self.walkTargetPos: Vector3(71.787323, 18.307215, 76.405022), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 9.470076560974121, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:33:09 292] - self.walkTargetPos: Vector3(88.131393, 18.294531, 72.591843), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 9.912796020507812, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:33:15 292] - self.walkTargetPos: Vector3(77.491516, 18.328426, 80.813484), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 11.003137588500977, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:33:21 292] - self.walkTargetPos: Vector3(82.086037, 18.294531, 67.809433), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 4.118252754211426, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:33:28 292] - self.walkTargetPos: Vector3(77.738754, 18.320456, 73.422455), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 3.720552682876587, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:33:35 292] - self.walkTargetPos: Vector3(80.811852, 19.279524, 63.859207), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 6.661016941070557, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:33:42 292] - self.walkTargetPos: Vector3(86.310776, 18.296234, 72.302010), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 8.092080116271973, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:33:49 292] - self.walkTargetPos: Vector3(89.663361, 18.294531, 66.249886), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 11.65351676940918, moveRange: 10.0
  S_WARN    cellapp01 12000 8001120  [2016-09-22 15:33:56 291] - self.walkTargetPos: Vector3(91.648636, 18.294531, 71.633728), ref=false, self.spawnPos: Vector3(78.623093, 17.518082, 69.898727), ref=false, distance: 13.163505554199219, moveRange: 10.0

self.spawnPos is centerPos, self.walkTargetPos is result, moveRange is maxRadius.

**Comment by Janiels** [comment]
This is intentional. The radius does not limit the picked point - it limits the polygons picked. That is, only polygons that intersect/are contained in the circle specified will be candidates to contain the random point.

**Comment by lupurs** [comment]
Thank you.

**Comment by grahamboree** [comment]
This is already documented in DetourNavMeshQuery.h so I think it's safe to close this.
