### ISSUE TITLE
Port of Detour in Golang

### ISSUE THREAD

**Issue by aurelien-rainone** [recastnavigation/recastnavigation#243]
Hi there,

I am currently porting Detour to the Go language, that I am going to integrate on the server of a multiplayer zombie RPG tower-defense like zombie indie game :stuck_out_tongue_closed_eyes: .

First i wanted to tell you about that. Second, I'd like to know if you are ok with how i credited Detour in the credits section of my README, and with the licensing.

Keep up the good work

See https://github.com/aurelien-rainone/go-detour

**Comment by grahamboree** [comment]
Seems fine to me, though I'm by no means an expert on these things!

**Comment by hymerman** [comment]
Exact same comment from me! I guess @memononen will be the one to rubber-stamp this since he's mentioned in the copyright?

**Comment by gyf19** [comment]
+1

**Comment by hymerman** [comment]
I think Mikko has taken a break to pursue carpentry or gardening or being a father or something, so I'm going to go ahead and say on his behalf that this is fine :)
