### ISSUE TITLE
Assertion failure custom functions

### ISSUE THREAD

**Issue by domalb** [recastnavigation/recastnavigation#251]
Hi there,

Integrating the library in our own engine, we added some small features to it.
So I'm proposing to report them back.

I started with assertions, and the ability to set a custom callback.
It is inspired by the already implemented allocation custom functions.
That way, any recast/detour assertion failure can be caught and rerouted for specific handling.
By default, the behavior has been left unchanged, which is the system 'assert' macro.

I made this pull request
https://github.com/recastnavigation/recastnavigation/pull/250
Could someone review it and give feedback ?

**Comment by jakobbotsch** [comment]
Closed in #250
