### ISSUE TITLE
Area bitwise manipulation

### ISSUE THREAD

**Issue by domalb** [recastnavigation/recastnavigation#257]
Hi all,
I noted that @bryanmcconkey expresses in issue https://github.com/recastnavigation/recastnavigation/issues/81 the need of working bitwise with areas.
I got the same need on my side.
It is quite clear: in some use cases (more complex than a handful of area ids, or data-driven engines) multiple systems interacts with the path finding generation. But they do not know each other, and the combinations of area ids is huge.
E.g. 4 types of units, each one with it's no-go zones, makes 16 combinations. But it's only a matter of 4 independent flags, after all !

According to me, this feature is nice to have to make it scalable in a modern game engine.
I propose to make a PR for it.
Are you open to that ?
Would you have some requirements or advices before I commit ?

Regards

**Comment by jakobbotsch** [comment]
Thanks for doing this in #260!
