### ISSUE TITLE
Infinite loop on large or invalid path request

### ISSUE THREAD

**Issue by TheNoobCompany** [recastnavigation/recastnavigation#261]
I have the same issue as in this issue: 
https://github.com/recastnavigation/recastnavigation/issues/45
https://github.com/recastnavigation/recastnavigation/issues/178

I'm running with a slitghly modified version of RecastNavigation but, it does includes all the fixes for "Maxnodes".

Let me know if I can do any interesting logging.

I can provide a patch file of all my modifications  privatly if necessary.

Note: In the target game distance, "yards".
I can generate path up to 13000 yards without issue but yet it would infinite loop on path  of ~4000yards sometimes.

Also: Does Recast/Detour can works in a multi-threaded environment if 2 path are requested from 2 differents threads at the same time or that would be a major issue and probably the source of my problem ?

**Comment by jakobbotsch** [comment]
Recast and Detour is not thread safe; you should not use `dtNavMeshQuery` simultaneously from different threads. You can create multiple instances and attach them to the same `dtNavMesh` instance - this is safe. `dtNavMesh` is also safe to use from multiple threads, but only for reading (i.e. no `addTile` calls and the likes).
