### ISSUE TITLE
Issue with point on edge of polygon in dtPointInPolygon?

### ISSUE THREAD

**Issue by killabi** [recastnavigation/recastnavigation#263]
We're trying to lock our characters to the nav mesh to simplify their movement update in our game, and I believe that we've ran into a bug with the dtPointInPolygon calculation.

I use a navigation raycast to see if movement will work, and correct the pawn to the hit location from the query if it is rejected, but a subsequent request will fail to find a valid start location. It appears that the problem is that dtPointInPolygon rejects points that are on the polygon edge.

In my example, I have a polygon that is (-1416, 2736), (-1476,2724), (-1500, 2772), (-1416, 2952) and a point that is (-1416, 2892). The first test (between points 3 and 0) fails for this point even though it is directly on the edge of the polygon.

I believe that changing '(pt[0] < (vj[0]-vi[0]) * (pt[2]-vi[2]) / (vj[2]-vi[2]) + vi[0])' to '(pt[0] <= (vj[0]-vi[0]) * (pt[2]-vi[2]) / (vj[2]-vi[2]) + vi[0])' will correct the issue.

Thoughts?

Thanks,
Chris W.

**Comment by killabi** [comment]
Actually, looking at this more, I'm not sure I understand this function at all? It appears to only test edges that the point falls within on the z-axis. Also, I don't understand why it flips the return value on subequent hits.

Is this code performing as intended?

Thanks,
Chris W.

**Comment by killabi** [comment]
It looks like this is an exclusive use of the even-odd test, but I wonder if an inclusive use would be better. Given that there can be gaps in the navmesh where the character cannot reach, it seems good to ensure that any overlap with a polygon is counted, even if that potentially produces overlaps with multiple polygons who share an edge.

I'm not sure the effect that changing this would have on the rest of the system, however.

Chris W.

**Comment by jakobbotsch** [comment]
In general even changing that check to `<=` you will be at the mercy of the floating point gods.

Instead there probably is a better way to accomplish what you are trying to do (i.e. take small epsilon into account).
Can you share the code you are using?

**Comment by killabi** [comment]
I'm running a NavQuery.raycast to compute a HitLocation (calculated using the HitTime). When I run a subsequent NavQuery.findNearestContainingPoly, I don't get one back for the computed hit location that lies on certain edges of the polygon.

An epsilon may be in order - but I'm not sure of the modification to make to the algorithm to make it include the points along any of the edges. I'm currently experimenting with padding the hit time back to produce better results.

**Comment by killabi** [comment]
Offsetting back a small bit from the hit location fixed the issue. It's a workaround, but seems to be working well.

**Comment by jakobbotsch** [comment]
This does not sound like regular Detour API.
`dtNavMeshQuery::raycast` returns the polygons that were traversed during the raycast - there should be no need to follow it up with (what I am assuming is) `dtNavMeshQuery::findNearestPoly`. Simply pick the last polygon from the list. `dtNavMeshQuery::findNearestPoly` also accepts extents and will not require the point to be directly 2D-contained in the polygon.

**Comment by hymerman** [comment]
Agreed with @jakobbotsch - is the API you're using different to this, @killabi ? If it's different, it's an issue with the API, if it's the same then just follow Jakob's suggestion. Numerical imprecision is a pain :)

**Comment by jakobbotsch** [comment]
Closing under the assumption that it is a different API. Feel free to reopen with more details @killabi!

**Comment by jackpoz** [comment]
I encountered a similar issue when x,y,z 3328.058838 287.074432 -3476.44091 with a raycast hit of around 0.5 (plus some small value) that would result in a point outside of the last polygon, causing getPolyHeight() to fail. With such big coordinates it's easy for a floating point to be not precise enough.

One confusing thing is that recastdemo doesn't check the return value of getPolyHeight() at https://github.com/recastnavigation/recastnavigation/blob/57610fa6ef31b39020231906f8c5d40eaa8294ae/RecastDemo/Source/NavMeshTesterTool.cpp#L917-L928 so it looks like the ray is pointing to a point outside of the mesh, especially if start and end have a different Y coordinate (I might PR a fix for that)
