### ISSUE TITLE
No NearestPolygon returned after some time

### ISSUE THREAD

**Issue by TheNoobCompany** [recastnavigation/recastnavigation#265]
Hello,

I have an issue with `DetourStatus FindNearestPolygon(array<float>^ center, array<float>^ extents, QueryFilter^ filter, [Out] array<float>^% nearestPoint)`

After some time, it'll return "0" for a certain position in my meshes, if I restart my  application, and check the exact same path, it'll be fine, so looks like the mesh is not the issue.

Any idea what could somehow corrupt the _query instance over time ?

I'll be having a work-arround => reinitialize the pathing system if I don't have a valid nearest polygon, but that issue is not really easy to reproduce unfortunatly so I don't know if it'll fix my problem.

**Comment by hymerman** [comment]
I guess given the `^`, `&` and `[Out]` that you're using a managed wrapper around Recast, right? If you're finding objects become corrupted, I'd suspect something in the wrapper. I haven't heard of any problems like this in the native library. When you say 'return 0' do you mean `nearestPoint` is the zero vector? What's the return code from the function - is it failing?

**Comment by TheNoobCompany** [comment]
I'm using a managed wrapper to be run from C# yes.

My C# app call the function that returns a "dtPolyRef" as ulong.
`public ulong FindNearestPolygon(float[] center, float[] extents, QueryFilter filter);`

```
		DetourStatus FindNearestPolygon(array<float>^ center, array<float>^ extents, QueryFilter^ filter, [Out] array<float>^% nearestPoint)
		{
			pin_ptr<float> centerPointer = &center[0];
			pin_ptr<float> extentsPointer = &extents[0];

			nearestPoint = gcnew array<float>(3);
			pin_ptr<float> nearestPointer = &nearestPoint[0];

			dtPolyRef discard;
			return (DetourStatus)_query->findNearestPoly(centerPointer, extentsPointer, filter->GetNativeObject(), &discard, nearestPointer);
		}

		dtPolyRef FindNearestPolygon(array<float>^ center, array<float>^ extents, QueryFilter^ filter)
		{
			pin_ptr<float> centerPointer = &center[0];
			pin_ptr<float> extentsPointer = &extents[0];
			dtPolyRef ret;
			if (_query->findNearestPoly(centerPointer, extentsPointer, filter->GetNativeObject(), &ret, 0) != DT_SUCCESS)
				return 0;
			return ret;
		}

```

I don't have a logging as you can see, but it doesn't return "DT_SUCCESS" so, it gives me "0" instead. (sorry for the confusion)

I need to think of an easy way  to send C++ logs to my C# logger so I can log the dtStatus when it happend.

**Comment by aurelien-rainone** [comment]
You could provide your own implementation of rcContext, look at how it's
done for BuildContext, in particular the `doLog` protected method, see
https://github.com/recastnavigation/recastnavigation/blob/master/RecastDemo/Include/SampleInterfaces.h

**Comment by hymerman** [comment]
Did you get this resolved @TheNoobCompany ? Any more input or insight?

**Comment by hymerman** [comment]
Actually I'm convinced this isn't a problem with our project so I'll close this for now to keep the bug tracker tidy; please follow up if you have more information though!
