### ISSUE TITLE
Detour obstacle, circle with parameters of position and radius

### ISSUE THREAD

**Issue by evgeny-detkov** [recastnavigation/recastnavigation#272]
Hello! I have a question...
I need to build a path by implementing an obstacle detour. But the requirement is as follows: there are the coordinates of the point and the radius of the circle. It is required to build a path around the circle.
"Sample_TempObstacles" as an example can not be used in my case.
Need to make an upgrade to "dtNavMeshQuery :: findStraightPath" to exclude the circle from consideration. I understand correctly? Any ideas or suggestions?

**Comment by evgeny-detkov** [comment]
Other question: whether it is possible to calculate a way in a detour of the agent (without usage addObstacles) if that is in one point motionlessly?

**Comment by jakobbotsch** [comment]
Mikko has blogged about a potential implementation of this before: http://digestingduck.blogspot.dk/2011/02/very-temporary-obstacle-avoidance.html
http://digestingduck.blogspot.dk/2011/02/very-temporary-obstacle-avoidance-pt-2.html

However, the implementation with temporary obstacles is much simpler to use and works much better in practice. It will be hard to adapt `findStraightPath` to take into account both the polygons and additional circular obstacles.

**Comment by evgeny-detkov** [comment]
I already tried to use addObstacle, I need it for the server. Tested on a large number of starts adding / removing obstacles - too long miscalculation.
Well ok .. I'll find more options.
