### ISSUE TITLE
Removing DU_DRAW_QUADS

### ISSUE THREAD

**Issue by sagaceilo** [recastnavigation/recastnavigation#276]
As most of You know, nowadays, there is no QUAD primitive. Especially when You work with Core Profile OpenGL or DX. What do You guys think about removing this primitive from debug drawer ? Maybe there should be virtuals for passsing point/line/triangle/quad in duDebugDraw so engine would handle quad as a two triangles instead ?

It could be done by having branch in virtual vertex(...) and when 4th vertex comes, just split four cached vertices to two triangles. But that seems hacky to me.

Whats would be even better is to have custom isVisible in duDebugDraw that passes bounding box of current tile. This way You can hook up frustum culling when rendering debug mesh of vast views. Currently I had to duplicate most of the rendering methods from the lib to inject this frustum pass.

**Comment by grahamboree** [comment]
Appreciate this suggestion!  While this is an interesting idea I'm not certain it's the right move here.  Being able to specify quads simplifies the debug-draw calling code in multiple locations at the expense of an additional method for subclasses of `duDebugDraw` to implement.

The intention with debug draw code like this is mostly there just to provide hooks for games or game engines to provide their own implementations of drawing routines.  Also where it's debug draw, there's been very little effort put towards making things fast or hardened.

That being said, it's worth providing the ability for folks like you with extreme circumstances to enhance the default behavior as needed.  I feel like that flexibility is already provided with the current debug draw system.  

If people wanted to re-implement the default quad drawing as a method that explicitly draws two triangles instead, I think that's a PR worth considering though!
