### ISSUE TITLE
Consider Emscripten or WebAssembly builds?

### ISSUE THREAD

**Issue by donmccurdy** [recastnavigation/recastnavigation#285]
Hi!

It would be *amazing* to be able to use Recast and Detour with WebGL/WebVR libraries like [three.js](https://threejs.org/), [BabylonJS](https://www.babylonjs.com/), [A-Frame](https://aframe.io/), and [ReactVR](https://facebook.github.io/react-vr/). Have you considered (or would you consider) including an Emscripten or WebAssembly compilation of the library?

Someone managed to do an [Emscripten compilation of Recast](https://github.com/vincent/recast.js) a few years ago, but it hasn't been maintained since then, and the demos appear to be broken.

If this isn't something you have time to build, would you consider accepting a PR that includes the compiled Emscripten or WebAssembly, and the build script to update them, so that they can be kept up to date with future changes?

Thanks!

**Comment by jakobbotsch** [comment]
Hi,

I am not sure that we would accept a precompiled binary (mostly due to security reasons), but we would gladly accept a build script for it. Note that I am not opposed to keeping precompiled binaries on this repo (it has been requested before), but making sure they are clean when we accept a PR would be very hard. I would have no problem using your build script to create precompiled binaries as a release.

**Comment by donmccurdy** [comment]
That makes great sense. I will see if I can make progress, and/or ask around for help. 🙂

**Comment by LiamKarlMitchell** [comment]
Yes please.

**Comment by jakobbotsch** [comment]
I will close this for now as it is not something we plan to do. However, we would gladly accept a contribution of the appropriate build scripts.

**Comment by donmccurdy** [comment]
No problem. I spent some time on this but didn't get it working, mostly I'm not familiar enough with the toolchain. I've been using a [node.js native addon](https://github.com/but0n/recastCLI.js) (running on a server) rather than using WASM in the browser meanwhile.

**Comment by donmccurdy** [comment]
Looks like the BabylonJS team managed to get this working!

https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release/recast.js

**Comment by GGAlanSmithee** [comment]
For future googlers, the Babylonjs team has an Emscripten port that they use internally, but is available stand-alone as well.

* https://www.npmjs.com/package/recast-detour
* https://github.com/BabylonJS/Extensions/tree/master/recastjs

it works as expected from what I've been able to test so far!
