### ISSUE TITLE
Define meaningful const instead of using un-meaningful magic number

### ISSUE THREAD

**Issue by hdnshare** [recastnavigation/recastnavigation#291]
I look at Recast detour source code and it takes me a while or even longer to digest the source code. I think it is not really good for maintain. I suggest using #define macro to solve this issue.
For example:
[this code](https://github.com/recastnavigation/recastnavigation/blob/2c85309280dbc9c82029e7ab16dfb01b9235c74e/Recast/Source/Recast.cpp#L277)
`const int* tri = &tris[i*3];
calcTriNormal(&verts[tri[0]*3], &verts[tri[1]*3], &verts[tri[2]*3], norm);`
We can replace the number 3 with:
`#define TRIANGLE_VERTICLE 3`
Then the code should be
`const int* tri = &tris[i*TRIANGLE_VERTICLE];`
Then we can quickly grab the idea, tri is the "i th triangle". At least we won't scratch the head and wonder: what is the number 3, is it 3 dimensional or 3 verticals?
I think the macro is good because it just tell the compiler to copy the define value that paste there at compile time - not effect the run-time performance, plus you get a better meaningful code which is priceless for maintain the code at long run.

**Comment by hdnshare** [comment]
It did took me awhile to figure out
`const int* tri = &tris[i*3];`
=
```
//Triangle --> std::vector<int> with 3 item, each item is the index point to the vertical of the triangle
std::vector< Triangle > arrTris; //Array of triangles
Triangle tri = arrTris[i]; //i th Triangle
```
And
`&verts[tri[0]*3]`
=
```
//Vector3 --> std::vector<float> with 3 item
Triangle tri;    //The triangle, contains 3 index, each index point to the vertical of the triangle from the vertical array
Vector3 vert[3]; //The vertical of the triangle above (A triangle has 3 vertical)
std::vector< Vector3 > arrVerts; //Array of all vertical in the scene
vert[0] = arrVert[ tri[0] ]; //Verticle 0 of the triangle
vert[1] = arrVert[ tri[1] ]; //Verticle 0 of the triangle
vert[2] = arrVert[ tri[2] ]; //Verticle 0 of the triangle
```

**Comment by jakobbotsch** [comment]
While I agree that it is not extremely clear at a first view, I do not think such a constant would improve the situation (high noise-to-signal when reading).
Once you have looked at the code base for a bit it becomes quite easy to navigate through the *3's. Some places in the code base could use some cleanup to use more intermediate variables though (this helps a lot too).
