### ISSUE TITLE
Agent avoidance issue.

### ISSUE THREAD

**Issue by Teiya** [recastnavigation/recastnavigation#295]
![img20171219_194014](https://user-images.githubusercontent.com/10287303/34155648-31f456b0-e4f5-11e7-8527-744efcb38f62.png)

It is difficult to find a way to the target position when there is several agent standing before, the agent is keep walking around with a very small speed. Is there any solution for this case?

**Comment by zhizhen** [comment]
We got the same problem, any solutions?

**Comment by grahamboree** [comment]
Velocity obstacles can address this kind of inter-agent collision avoidance behavior.  DetourCrowd has a limited implementation of velocity obstacles, but not any way to directly address this problem out of the box.
