### ISSUE TITLE
Got memory error when i run  RecastDemo

### ISSUE THREAD

**Issue by liuyihunter** [recastnavigation/recastnavigation#298]
I built project in "VS2017", there are no errors in build process.  But i got memory error when i run "RecastDemo".

![image](https://user-images.githubusercontent.com/3315302/34516535-2780fc6a-f0b2-11e7-8226-b7fbfe195c41.png)

![image](https://user-images.githubusercontent.com/3315302/34516189-f3006cce-f0b0-11e7-9d70-f6eb08f74f6b.png)

![image](https://user-images.githubusercontent.com/3315302/34516197-00033dca-f0b1-11e7-869a-e5da2bd99993.png)

**Comment by jakobbotsch** [comment]
I am unable to reproduce this. Can you give the exact steps used?

**Comment by jakobbotsch** [comment]
Since I cannot reproduce this I'm going to close the issue. If you can provide steps, please do and reopen the issue.
