### ISSUE TITLE
RecastDemo: agents overlapping

### ISSUE THREAD

**Issue by hsdxpro** [recastnavigation/recastnavigation#305]
Hi guys, I've noticed agents are overlapping(not all of them) even if they move, is it configurable or is it a real issue?

![image](https://user-images.githubusercontent.com/5315603/34849599-32662e1c-f723-11e7-9ee7-6b4dd7062909.png)

**Comment by LiamKarlMitchell** [comment]
Is Separation enabled what about using a larger weight?

**Comment by hsdxpro** [comment]
Good tip !


I turned on separation and maximized it's value before spawning agents:
![image](https://user-images.githubusercontent.com/5315603/34872007-bc6e3e6c-f78f-11e7-82b5-07a5c8717c19.png)

**Comment by hsdxpro** [comment]
A new test.

Aftre I moved them outside of this overlaps slowly disappeared which is good. But after I moved back them to this place overlaps again occured, despite there is enough space for every agent.

![image](https://user-images.githubusercontent.com/5315603/34872416-0a43658a-f791-11e7-982d-98476198717d.png)

**Comment by hsdxpro** [comment]
Any answer highly appreciated because I'm going to integrate the library into a very serious ( urgent ) project, which is now using Unity's built-in (works just fine), hope this version will work similarly.

**Comment by mimooh** [comment]
I confirm, the agents overlap when things get crowded and I need hundreds of agents. Separation doesn't solve the issue, plus it adds unnatural spacing when set to high values.

**Comment by Aaricis** [comment]
Hi! Could you please tell me how to run `RecastDemo`? I run `RecastDemo\Bin\RecastDemo`, but I see nothing.
![2018-05-11 11-00-53](https://user-images.githubusercontent.com/35218694/39904549-19177eca-550b-11e8-9ba4-95112710c986.png)

**Comment by mimooh** [comment]
From what I can recall, I managed to install and launch, but the app looked similar and was crashing after clicking. It helped to install more of libsdl2, like libsdl2-gfx-dev and some more libsdl2- maybe.

I suggest you try adding one package at a time, find what solves the problem and then inform the developers that updating the installation instructions could be useful, because you're not the first to run into this problem. The docs now state:

Linux
Install SDL2 and its dependencies according to your distro's guidelines.

Which is not that obvious that just apt-get install libsdl2-devel is not enough

**Comment by hsdxpro** [comment]
Choose sample and mesh from the list ! @Aaricis 

![image](https://user-images.githubusercontent.com/5315603/39916994-721bc53e-550c-11e8-93b4-0b0e069400bf.png)

**Comment by Aaricis** [comment]
Thanks a lot!!!!!! I have got it. @hsdxpro  @mimooh

**Comment by Bromeon** [comment]
Increasing the number of
```static const int MAX_NEIS = 32;```
in [DetourCrowd.cpp](https://github.com/recastnavigation/recastnavigation/blob/master/DetourCrowd/Source/DetourCrowd.cpp#L194) seems to work around this problem for small numbers.

It's obviously not a robust solution, as it just shifts the problem to a bigger number of agents, but it might serve as a start for looking into the underlying problem.

**Comment by grahamboree** [comment]
Moved to #305 as this is a more involved issue than just increasing `MAX_NEIS`
