### ISSUE TITLE
Compilation Error in RecastDemo

### ISSUE THREAD

**Issue by severin-lemaignan** [recastnavigation/recastnavigation#31]
When compiling with Ubuntu 14.04 (`g++-4.8.2`), compilation fails in `RecastDemo/Source/CrowdTool.cpp`

- l.158: `error: no matching function for call to ‘dtCrowd::getEditableFilter()’`
- l.710: `error: no matching function for call to ‘dtCrowd::getFilter()’`

Adding a parameter (`0`) to these function workaround the issue.

**Comment by hymerman** [comment]
Looks like this was fixed by Mikko in d477061f83258ad64201f56ca0d3cc1856870fff so I'll close this now.
