### ISSUE TITLE
`dtTileCache::buildNavMeshTile`  have not `PolyMeshDetail` info ?

### ISSUE THREAD

**Issue by fananchong** [recastnavigation/recastnavigation#312]
in function dtTileCache::buildNavMeshTile no build `PolyMeshDetail` info

**Comment by jakobbotsch** [comment]
This is intended. The tile cache should only be used with very small tile-sizes, and the smaller the tiles are, the less necessary a detail mesh is.
If you have large inaccuracies, your tile size is probably too large.
