### ISSUE TITLE
Different anent radius problems after build

### ISSUE THREAD

**Issue by DDFighting** [recastnavigation/recastnavigation#325]
> https://lh3.googleusercontent.com/-G9fr5EaDTJM/Wv0YQJTzjJI/AAAAAAAAAEU/pH2boLdlx1UTBtggtEIbUmxw7zr1_GsuwCLcBGAs/s1600/DW%257B%257DB%2524VD6N10%2524CVJL2M%257E5TU.png

I build it according to the A's radius, but I have agent of different sizes. like B. 
Part of the B will go beyond the navmesh.
How to deal with this situation.

I haven't used UE or U3D, and I'm not sure how they handle them. I heard that they are all improved by the author of recast.

Thank you for help!!

**Comment by jakobbotsch** [comment]
The best way to deal with this is to build multiple meshes. There is no good/supported way of allowing agents of different radii to operate on a single nav mesh. You can try to mark polygons close to edges as another area type and ability flag, but that creates many polygons and other problems.

There's some more information in the comments to these blog posts:
http://digestingduck.blogspot.dk/2010/05/towards-better-navmesh-path-planning.html
http://digestingduck.blogspot.dk/2010/08/path-following-performance.html

**Comment by DDFighting** [comment]
Thank you for your reply and get some inspiration！

> https://lh3.googleusercontent.com/-lkxtvN1e93U/Wv58qNKypII/AAAAAAAAAEg/wge0KXsjFe4t1UHda9V_V4Sr4gTjV_X9wCLcBGAs/s1600/1VR%2529D%255BZO91CYTJDF%25405TQM%2540C.png

> https://lh3.googleusercontent.com/-NRKccTYnBRU/Wv58s7hiDCI/AAAAAAAAAEk/hfdOyQCzm2EqJJIVXWVaSKGhzW7gRMd7gCLcBGAs/s1600/KBDFR1%2525%257EG%255D_3TOUNGF7SEYR.png

Pathfinding above version 5.6 in U3D can already set multiple radius agents.
I currently use physics engine collision to solve my problem.
