### ISSUE TITLE
About function dtNavMeshQuery::findRandomPoint

### ISSUE THREAD

**Issue by fananchong** [recastnavigation/recastnavigation#329]
the code in function dtNavMeshQuery::findRandomPoint :
```c++
	// Randomly pick one tile. Assume that all tiles cover roughly the same area.
	const dtMeshTile* tile = 0;
	float tsum = 0.0f;
	for (int i = 0; i < m_nav->getMaxTiles(); i++)
	{
		const dtMeshTile* t = m_nav->getTile(i);
		if (!t || !t->header) continue;
		
		// Choose random tile using reservoi sampling.
		const float area = 1.0f; // Could be tile area too.
		tsum += area;
		const float u = frand();
		if (u*tsum <= area)
			tile = t;
	}
	if (!tile)
		return DT_FAILURE;
```

instead of:

```c++
int i = int(frand() * m_nav->getMaxTiles());
auto tile = m_nav->getTile(i);
```

then the time complexity is O(1)

**Comment by jakobbotsch** [comment]
You would need to retry if `tile->header` was null, but yes, that would work too. I think @memononen wanted to eventually make tile selection weighed by area (as you can see by the comment).
One good thing about the current implementation is that the performance is consistent, even if consistently bad. You can imagine your approach in a situation where only very few tiles are loaded out of many thousands of tiles -- its performance characteristics would vary wildly, based on how early a loaded tile was selected. I think for that reason I prefer the current implementation.

**Comment by jakobbotsch** [comment]
Random + linear scan with wrap around is a good idea, that's a new one for me. 

The benefit from keeping track of the biggest tile index use is probably not that large, since they are not loaded sequentially, so you can have the largest index loaded as the only tile.

I would be happy to take a PR with the random + linear scan as suggested by Mikko. It seems like a clear winner.

**Comment by jakobbotsch** [comment]
On second thought, random + linear scan could be pretty biased in certain situations, for example if you have two tiles loaded coming right after each other. The last one would almost never be selected compared to the first one.

**Comment by memononen** [comment]
Randomized access to array with gaps is pretty much the same problem as hash map with collisions (but kinda reverse). In hash map lingo the random + linear is called linear probing.

Random+linear solves the worst case behavior of random+retry, but probably does not give very good random number as you point out. You could keep track a compacted array of "active tiles" on add/delete tile, though.

**Comment by fananchong** [comment]
I think it's too simple. Learned
