### ISSUE TITLE
Navmesh data saving and loading

### ISSUE THREAD

**Issue by MaxHayman** [recastnavigation/recastnavigation#341]
Hello,

I have been watching this project and really would like to get it working in my project.

We have heightmap files which we generate landscape and then objects which go on top.

Am I right in thinking ideally i would merge the heightmap and objects into a triangle soup first?

However i was going to start loading the landscape and producing a navmesh for that. However, I am wondering how the best way to test this resultant navmest. 

Ideally I would like to generate the navmest from the heightmaps then test it by loading it into RecastDemo. Then later work on using detour to do the pathfinding. However can RecastDemo only import model files? or can it load in intermediate navmesh?

Currently i was testing by exporting the landscape as an obj file and loading it into RecastDemo.

Just some guidance would be greatly appreciated.

**Comment by jakobbotsch** [comment]
> Am I right in thinking ideally i would merge the heightmap and objects into a triangle soup first?

Typically yes, a triangle soup is rasterized to create the heightfield. However it is also possible to load a heightmap directly into the heightfield. I have recently answered a question like this [here](https://groups.google.com/forum/#!topic/recastnavigation/xUZdVH-pAE0). Although I would not recommend this approach if you have other kind of data too, or multiple overlapping heightmaps.

> However can RecastDemo only import model files? or can it load in intermediate navmesh?

The demo can save and load its own created nav-meshes with the `Save` and `Load` UI buttons. The code behind is [here](https://github.com/recastnavigation/recastnavigation/blob/05b2b8da80037887d3e79af8a59a8f0f8ed02602/RecastDemo/Source/Sample_TileMesh.cpp#L281-L286). You could potentially output meshes in the correct format and load it this way.
However you should note that the demo is not really meant to be used in this way. It is meant to demonstrate the functionality -- usually you would create your own visualizer for your own application which would support saving and loading things in your format.
