### ISSUE TITLE
Use DetourCrowd with external physics

### ISSUE THREAD

**Issue by elsid** [recastnavigation/recastnavigation#344]
dtCrowd handles movement for agents internally. After each update there is new position for each actor. Calculation of a new positon includes maximum velocity and acceleration of agent. Also there is specific [logic](https://github.com/recastnavigation/recastnavigation/blob/05b2b8da80037887d3e79af8a59a8f0f8ed02602/DetourCrowd/Source/DetourCrowd.cpp#L59-L75) how to change agent speed.

Is there some way how can I use external physics to update agent position for given time interval and use custom logic for agent speed?

For example agent speed is constant, there is no acceleration, so in each moment of time agent could move in specific direction or stay. Agent can change direction instantly.

I see this as customization point for dtCrowd class. Probably add an interface class and default implementation with current logic. Will you approve this kind of change or is there any other way? Thanks.

**Comment by jakobbotsch** [comment]
I believe the main thing is that keeping the agent on mesh can be a problem if the Detour does not have full control over the movement, and if the agent gets off mesh then that causes a bunch of problems. @memononen has posted more details about it somewhere I'm sure, but I can't find it at the moment.

Unfortunately DetourCrowd is the area of R&D I am the least familiar with so I am not able to provide much feedback on eventual PRs/work. Maybe @hymerman @grahamboree could help out?

**Comment by grahamboree** [comment]
Just to close the loop on this, there's no prescribed method to drop-in a new physics engine into DetourCrowd.  IMO there's probably some work that could be done to separate the code that does the simple physics to move the agent and the code that's driving that motion.  That would better support use cases like this.
