### ISSUE TITLE
For detail mesh, will polygons sharing edges have different decision about sample vertices?

### ISSUE THREAD

**Issue by MoYummy** [recastnavigation/recastnavigation#348]
Assume two polygons share same edges, which contains one sample vertex.
After testing with individual height patch data, left polygon considers it needed while right one does not. Is this case possible? If so, will this lead to seams?

**Comment by memononen** [comment]
The code should be deterministic in that scenario:
https://github.com/recastnavigation/recastnavigation/blob/master/Recast/Source/RecastMeshDetail.cpp#L674

**Comment by MoYummy** [comment]
![image](https://user-images.githubusercontent.com/8344384/44619862-1d157c00-a8be-11e8-9313-3281925d269e.png)

**Comment by MINIONBOTS** [comment]
I also experience that a lot on tile borders, although they are build with overlapping input data, so in theory they should definitely merge on the edges...but they often don't .. Do you have a proposition how to fix that?

**Comment by grahamboree** [comment]
Hi!  Can you please provide steps to reproduce this problem and open a new issue containing those repro steps?
