### ISSUE TITLE
sdl2.dll path error

### ISSUE THREAD

**Issue by codentropy** [recastnavigation/recastnavigation#354]
hi, i use VS2015 compile this,  it says "Contrib/SDL/lib/x86/SDL2.dll file not found" when trying to copy it into Bin. Maybe the path in premake5.lua
		postbuildcommands {
			-- Copy the SDL2 dll to the Bin folder.
			'{COPY} "%{wks.location}../../Contrib/SDL/lib/x86/SDL2.dll" "%{cfg.targetdir}"'
		}
should be supplemented like
		postbuildcommands {
			-- Copy the SDL2 dll to the Bin folder.
			'{COPY} "%{wks.location}../../../../Contrib/SDL/lib/x86/SDL2.dll" "%{cfg.targetdir}"'
		}
, but i have't tested on other VS release versions.
However, this error does not affect the output exe file, it runs fine.

**Comment by jakobbotsch** [comment]
Did you download SDL2 and unzip it so that the path `RecastDemo\Contrib\SDL\lib\x86` is valid? You can read more under the build instructions in the readme.

**Comment by codentropy** [comment]
yes, i did. It is weird that "premake5 vs2015"  generate 
    <PostBuildEvent>
      <Command>IF EXIST "Contrib\SDL\lib\x86\SDL2.dll"\ (xcopy /Q /E /Y /I "Contrib\SDL\lib\x86\SDL2.dll" "..\..\Bin" &gt; nul) ELSE (xcopy /Q /Y /I "Contrib\SDL\lib\x86\SDL2.dll" "..\..\Bin" &gt; nul)</Command>
    </PostBuildEvent> 
in RecastDemo.vcxproj file. Maybe this issue is up to premake-core. I compile premake5 by VS2015 in win10 64bit.

**Comment by jakobbotsch** [comment]
That is strange, I get the expected:
`IF EXIST "$(SolutionDir)..\..\Contrib\SDL\lib\x86\SDL2.dll"\ (xcopy /Q /E /Y /I "$(SolutionDir)..\..\Contrib\SDL\lib\x86\SDL2.dll" "..\..\Bin" &gt; nul) ELSE (xcopy /Q /Y /I "$(SolutionDir)..\..\Contrib\SDL\lib\x86\SDL2.dll" "..\..\Bin" &gt; nul)`
(and equivalent for x64) in both vs2015 and vs2017.
By the way, I notice that you aren't using the newest bits, so maybe try updating (the postbuildcommands in the premake file now takes x64/x86 into account).

Do you get the same behavior with a prebuilt binary from [here](https://premake.github.io/download.html)? Also, does the file path containing the sources contain any strange characters?

**Comment by codentropy** [comment]
Thank you for suggestions! The prebuilt binary premake5 does correct it by generating the complete path argument as yours. Please close this issue. :-)

**Comment by jakobbotsch** [comment]
Thanks for confirming, I will try to take a look at premake and see if it is something that should be reported.
