### ISSUE TITLE
Clang 3.6 warnings

### ISSUE THREAD

**Issue by psi29a** [recastnavigation/recastnavigation#362]
OpenMW now uses recastnavigation and we've pulled it into our tree (for now). In our Travis-CS matrix, one is compiling with clang which points out the following:

```
In file included from /home/travis/build/OpenMW/openmw/extern/recastnavigation/Detour/Source/DetourNavMeshQuery.cpp:24:
/home/travis/build/OpenMW/openmw/extern/recastnavigation/Detour/Include/DetourCommon.h:142:17: warning: The right operand of '-' is a garbage value
        dest[0] = v1[0]-v2[0];
                       ^~~~~~
/home/travis/build/OpenMW/openmw/extern/recastnavigation/Detour/Source/DetourNavMeshQuery.cpp:511:21: warning: Called C++ object pointer is null
        if (dtStatusFailed(m_nav->getTileAndPolyByRef(ref, &tile, &poly)))
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/OpenMW/openmw/extern/recastnavigation/Detour/Source/DetourNavMeshQuery.cpp:556:37: warning: Division by zero
                const float* vb = &verts[((imin+1)%nv)*3];
                                          ~~~~~~~~^~~
/home/travis/build/OpenMW/openmw/extern/recastnavigation/Recast/Source/RecastMeshDetail.cpp:586:2: warning: Function call argument is an uninitialized value
        tris.push(hull[start]);
        ^~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/OpenMW/openmw/extern/recastnavigation/Recast/Source/RecastMeshDetail.cpp:587:2: warning: Function call argument is an uninitialized value
        tris.push(hull[left]);
        ^~~~~~~~~~~~~~~~~~~~~

/home/travis/build/OpenMW/openmw/extern/recastnavigation/DetourTileCache/Source/DetourTileCacheBuilder.cpp:485:7: warning: Value stored to 'ndir' during its initialization is never read
                int ndir = dir;
                    ^~~~   ~~~
/home/travis/build/OpenMW/openmw/extern/recastnavigation/DetourTileCache/Source/DetourTileCacheBuilder.cpp:1280:22: warning: The left operand of '&' is a garbage value
        *dst++ = indices[2] & 0x7fff;
                 ~~~~~~~~~~ ^
```

For tracking purposes:
https://github.com/OpenMW/openmw/pull/1633#issuecomment-435814832

**Comment by jakobbotsch** [comment]
I think a lot of these are false positives. For instance, for 2 and 3 Clang is just confused by our assertion macro. 4 and 5 is just an unnecessary check, again causing Clang to emit a false positive. Number 6 is true, but of course this one does not cause any problems. Finally I am also pretty sure 7 is a false positive as well.

Not sure about 1, Clang does not really give a lot of information about which call site is supposedly invoking this on garbage.

**Comment by psi29a** [comment]
Thanks for reviewing this. :)

Would you accept a PR if someone wanted to fix these warnings?

**Comment by jakobbotsch** [comment]
Yes, gladly (assuming we do not regress performance or similar!).

**Comment by psi29a** [comment]
That's the plan. Only no-ops or better. :)

**Comment by akortunov** [comment]
> for 2 and 3 Clang is just confused by our assertion macro.

For such cases Clang team suggests to mark a custom assertion function with the `__attribute__((analyzer_noreturn))` attribute, so Clang analyzer will recognize it as an assert.

So there should be something like this (just an example!):
```
#ifndef CLANG_ANALYZER_NORETURN
#if __has_feature(attribute_analyzer_noreturn)
#define CLANG_ANALYZER_NORETURN __attribute__((analyzer_noreturn))
#else
#define CLANG_ANALYZER_NORETURN
#endif
#endif

#define dtAssert(expression) CLANG_ANALYZER_NORETURN \
```

As for possible division by zero [here](https://github.com/recastnavigation/recastnavigation/blob/master/Detour/Source/DetourNavMeshQuery.cpp#L556), probably there should be an explicit assertion with the `nv > 0` condition.

**Comment by jakobbotsch** [comment]
I am pretty sure that division-by-zero will disappear once the assertion macro is fixed. I think Clang is flagging it because `nv` comes from `poly`, and it believes `poly` to be possibly undefined to access.

**Comment by akortunov** [comment]
```
/home/travis/build/OpenMW/openmw/extern/recastnavigation/Recast/Source/RecastMeshDetail.cpp:586:2: warning: Function call argument is an uninitialized value
        tris.push(hull[start]);
        ^~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/OpenMW/openmw/extern/recastnavigation/Recast/Source/RecastMeshDetail.cpp:587:2: warning: Function call argument is an uninitialized value
        tris.push(hull[left]);
        ^~~~~~~~~~~~~~~~~~~~~
```

I suppose the reason of this complaint is [here](https://github.com/recastnavigation/recastnavigation/blob/master/Recast/Source/RecastMeshDetail.cpp#L668) - if the sampleDist <= 0 for some reason, `hull` variable will remain uninitialized, despite the triangulateHull() function still will use it.

**Comment by jakobbotsch** [comment]
Indeed, but the check is unnecessary. Passing 0 for `sampleDist` would not result in anything useful even if it was supported. We should error out in `rcBuildPolyMeshDetail` in this case and then we can get rid of these checks.

**Comment by akortunov** [comment]
Just for reference: there is a full scan report (including context) with Clang 7: [scan-build-2018-11-09-102823-18838-1.zip](https://github.com/recastnavigation/recastnavigation/files/2566062/scan-build-2018-11-09-102823-18838-1.zip)
There are 23 warnings, related to Recast and Detour (/extern/recastnavigation folder).

**Comment by jakobbotsch** [comment]
Thank you, that helps a lot. There are definitely some bugs there. I will try to look at them over the weekend.

**Comment by jakobbotsch** [comment]
This is still on my radar, hopefully I will be able to fix (some of) these soon.

**Comment by psi29a** [comment]
Now that #366 is merged, we have some visibility on issues. :)
