### ISSUE TITLE
GCC8 Warning

### ISSUE THREAD

**Issue by psi29a** [recastnavigation/recastnavigation#363]
Tried out recastnav with GCC8 and got the following warning as well:

```
/home/travis/build/OpenMW/openmw/extern/recastnavigation/Detour/Source/DetourNavMesh.cpp: In member function ‘dtStatus dtNavMesh::init(const dtNavMeshParams*)’:
/home/travis/build/OpenMW/openmw/extern/recastnavigation/Detour/Source/DetourNavMesh.cpp:243:50: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct dtMeshTile’ with no trivial copy-assignment [-Wclass-memaccess]
  memset(m_tiles, 0, sizeof(dtMeshTile)*m_maxTiles);
                                                  ^
In file included from /home/travis/build/OpenMW/openmw/extern/recastnavigation/Detour/Source/DetourNavMesh.cpp:22:
/home/travis/build/OpenMW/openmw/extern/recastnavigation/Detour/Include/DetourNavMesh.h:276:8: note: ‘struct dtMeshTile’ declared here
 struct dtMeshTile
        ^~~~~~~~~~
```

**Comment by jakobbotsch** [comment]
The structure being cleared is just a POD type with deleted copy-constructor and assignment operator.

It appear GCC8 does not recognize the old-style idiom used for deleting auto-generated members (where you just declare them privately without an implementation). We use this approach to support older compilers.

Unfortunately the only workarounds I can think of involves ugly if-defs or undeleting these (which I am not a fan of as this type should not be copied).

**Comment by jakobbotsch** [comment]
In general we stay away from C++11+ features in the library parts. At some point we should probably reevaluate this decision (after all, C++11 is 7 years old at this point), but R&D is a big collection of algorithms at its heart and it is limited how many new features are actually useful in this sense. So until now we have erred on the side of compatibility.

**Comment by psi29a** [comment]
And now that C++11 is almost 9 years old? :)

**Comment by akortunov** [comment]
> The structure being cleared is just a POD type with deleted copy-constructor and assignment operator.

Just for reference - marking related methods as `delete` does not fix the warnings. I know that several projects tell compiler to treat the struct as a raw memory to silece the warning.
So the
```
memset(m_tiles, 0, sizeof(dtMeshTile)*m_maxTiles);
```
would become the
```
memset(static_cast<void*>(m_tiles), 0, sizeof(dtMeshTile)*m_maxTiles);
```

Not sure if such statement is valid for all compilers, supported by R&D, though.
