### ISSUE TITLE
dtIntersectSegmentPoly2D's way of determining collinearity of line segments

### ISSUE THREAD

**Issue by sk6868** [recastnavigation/recastnavigation#367]
dtIntersectSegmentPoly2D has the following logic:

```
		const float n = dtVperp2D(edge, diff);
		const float d = dtVperp2D(dir, edge);
		if (fabsf(d) < EPS)
		{
			// S is nearly parallel to this edge
```

Wouldn't d's error be proportional to both dir and edge?  As an example, dir and edge could be the sides of a very slender parallelogram (i.e. edge[2] is much much larger than edge[0]) where the angle between dir and edge is extremely small--in this situation, dir and edge are almost parallel, yet dtVperp2D(dir, edge) is much larger than EPS.

**Comment by jakobbotsch** [comment]
I think so, but I think this check is mainly for numerical stability of the division with `d` below. So if `d` is large, even if it close to parallel, we will get a good estimate of the intersection "far out".

Have you run into problems in this area?

**Comment by sk6868** [comment]
We are trying to validate the results of findPath using raycast.  That is to say, we are trying use raycast to validate each segment returned by findPath.  Since each startPos and endPos in a findpath segment are most likely the vertices of a navmesh, we would like raycast to return FLT_MAX for cases where the ray is collinear and overlapping with a navmesh polygon edge.

But we are finding that raycast will return a hitTime of 0 when startPos is a navmesh polygon vertex.

**Comment by jakobbotsch** [comment]
Can you share the polygon and query passed to `dtIntersectSegmentPoly2D`?

I agree that it is a little unintuitive that `raycast` hits something on a path returned by `findStraightPath`. But this is probably not too easy to solve without using a very sloppy epsilon, depending on the magnitude of the floating point numbers. If you share the data I can see if there is something obvious to do here.

Is there any reason you do not trust the results returned by `findStraightPath`? An alternative fix on your side might also be to just move the start points very slightly towards the end point of each segment.

**Comment by memononen** [comment]
The raycast was originally designed for sampling i.e. for steering. Points on the edge of the polygon are not very consistent as per @jakobbotsch says, and IIRC the code generally favors hit on parallel edges for that reason. The function has special feature that if the character is outside the polygon, the rays can enter into valid area.

There are so many floating point inaccuracies and non-deterministic code involved that raycast is not the best way to check if path is valid. Whether your intent is to use it for gameplay or unit testing.

A better way is to use `moveAlongSurface()`.
https://github.com/recastnavigation/recastnavigation/blob/master/Detour/Include/DetourNavMeshQuery.h#L374
It's more of a path find search than straight line check, and can handle small deviations in the path, but will get stuck in local minimas. You may need to split the calls for long segments (i.e. 10-20x agent radius).

More info about moveAlongSurface here: http://digestingduck.blogspot.com/2010/07/constrained-movement-along-navmesh-pt-3.html

**Comment by sk6868** [comment]
We are using findpath on the client side and trying to validate each segment returned by findpath using raycast on the server side.

I'm not sure moveAlongSurface will be useful for us since we need a way to check if each line segment (which we assume to be a straight line) in the result returned by findpath is indeed clear of any obstruction or partially outside the navmesh.

**Comment by memononen** [comment]
@sk6868 As discussed earlier, testing line segment against the navmesh is not robust operation. More robust way is to use topology instead, that is, the polygons and polygon connectivity. If you can formulate your test to use the list of polygons of the path instead of points, it will be much faster and more robust.

Can you describe more in detail why the validation is done? Is the validation for cheating detection, or to determine if the world has changed, or something else?

If you really, really need to check for the line segment, the most robust way is to use findPath() or moveAlongSurface() between the segment end points, get the resulting corridor polygons, call findStraightPath(), and check if resulting path is within tolerance of the segment (it is possible that findStraightPath() returns almost straight path with multiple points).
