### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by BizzyBee316** [recastnavigation/recastnavigation#370]
Hi guys,
I have this problem with navigation and I was wondering if anyone knows how to solve it.

If the diameter of the agent (Player) is longer than the height of a path, we want the player to stop in front of the path.  Right now, if I click on a destination past the path, the player walks through it even if its diameter is longer than the height of the path.

Please look at the below image for better understanding.
Any advise will be highly appreciated.

![image](https://user-images.githubusercontent.com/46276749/50557420-683a1280-0d28-11e9-850d-a0a46fc63530.png)

Thanks and happy new year!

**Comment by jakobbotsch** [comment]
Are you passing the diameter as the height when building the nav mesh? Normally there will not even be created nav mesh in areas where the agent cannot stand. Such regions are filtered away by `rcFilterWalkableLowHeightSpans` and `rcBuildCompactHeightfield`. You can play around in the demo to see what effect these functions have on the data.

**Comment by alexzk1** [comment]
dtStatus dtNavMesh::init(const dtNavMeshParams* params)

does not copy origin and all is broken then
