### ISSUE TITLE
Copy origin

### ISSUE THREAD

**Issue by alexzk1** [recastnavigation/recastnavigation#375]
dtNavMesh::init does not copy origin from supplied dtNavMeshParams and everything is broken. Remove those copies finally as you intendent in comments. Less then 20 changes, takes 5 mins with modern IDE.

**Comment by jakobbotsch** [comment]
The origin is copied here:
https://github.com/recastnavigation/recastnavigation/blob/14b2631527c4792e95b2c78ebfa8ac4cd3413363/Detour/Source/DetourNavMesh.cpp#L227

Not sure what you mean exactly, could you explain further?

**Comment by alexzk1** [comment]
weird, this line was absent in my copy...
any way, i deleted copies and put in use "params" .
