### ISSUE TITLE
aligments

### ISSUE THREAD

**Issue by alexzk1** [recastnavigation/recastnavigation#376]
Try to modify your funcs by adding static_assert:

```
template<typename TypeToRetrieveAs>
TypeToRetrieveAs* dtGetThenAdvanceBufferPointer(const unsigned char*& buffer, const size_t distanceToAdvance)
{
    static_assert (types_ns::TestAlignForStruct<TypeToRetrieveAs, 4>::value, "Wrong struct align");
    TypeToRetrieveAs* returnPointer = reinterpret_cast<TypeToRetrieveAs*>(buffer);
    buffer += distanceToAdvance;
    return returnPointer;
}

template<typename TypeToRetrieveAs>
TypeToRetrieveAs* dtGetThenAdvanceBufferPointer(unsigned char*& buffer, const size_t distanceToAdvance)
{
    static_assert (types_ns::TestAlignForStruct<TypeToRetrieveAs, 4>::value, "Wrong struct align");
    TypeToRetrieveAs* returnPointer = reinterpret_cast<TypeToRetrieveAs*>(buffer);
    buffer += distanceToAdvance;
    return returnPointer;
}
```
Where

```
template <class T, size_t N>
    struct TestAlignForStruct
    {
        using is_align1 = typename std::conditional<alignof (T) == N, std::true_type, std::false_type>::type;
        static constexpr bool value{std::conditional<std::is_class<T>::value, is_align1, std::true_type>::type::value};
    };

```

You should be getting many compilation fails where structs are not properly aligned explicit (tried on 64 bits). That is problem with save/load data between machines.

**Comment by jakobbotsch** [comment]
There are obviously several data types that do not require 4 byte alignment, so it is not weird that your assertion triggers. For example:
* https://github.com/recastnavigation/recastnavigation/blob/14b2631527c4792e95b2c78ebfa8ac4cd3413363/Detour/Source/DetourNavMesh.cpp#L925
* https://github.com/recastnavigation/recastnavigation/blob/14b2631527c4792e95b2c78ebfa8ac4cd3413363/Detour/Source/DetourNavMesh.cpp#L1329

Neither of these are required to be 4-byte aligned.

**Comment by alexzk1** [comment]
Last one I changed next
`#pragma pack(push, 4)
struct dtTileState
{
    int magic;                              // Magic number, used to identify the data.
    int version;                            // Data version number.
    dtTileRef ref;                          // Tile ref at the time of storing the data.
};

struct dtPolyState
{
    union
    {
        struct
        {
            unsigned short flags;                       // Flags (see dtPolyFlags).
            unsigned char area;                         // Area ID of the polygon.
        };
        uint32_t dumb;
    };
};
#pragma pack(pop)`

I think everything serialized to "unsigned char" must be aligned by 1. However, if total length is equal to 4, then can use align 4. Just didn't have time/mood to dig when needed, when not.

**Comment by jakobbotsch** [comment]
If something is 4-byte aligned it is also going to be 2 and 1-byte aligned. So I am not entirely sure what issue is being reported here. Please reopen if you find something wrong.
