### ISSUE TITLE
Can move between adjacent polygons with no edge.

### ISSUE THREAD

**Issue by erikwijmans** [recastnavigation/recastnavigation#377]
# Summary
In one of the meshes I am using recast with, there are two polygons that are adjacent, but have no navigation edge between them.  Therefore, I shouldn't be able to move between those two polygons via `moveAlongSurface`.  However, I am able to!

# Reproduce 
Steps to reproduce:
1. Get the navmesh and repro script: 
[problem_mesh.navmesh](https://drive.google.com/file/d/1QanhDtqAzjRA7uOKZdv-hXcGfbqKEgEC/view?usp=sharing)
[repro.cpp](https://pastebin.com/vXBwaFj8)
1. Compile the repro script: `g++ repro.cpp /path/to/recastnavigation/Detour/Source/* -I/path/to/recastnavigation/Detour/Include -o repro`
1. Run the repro script: `./repro`:

```
Start point in polygon 188
Target end in polygon 166
Distance between start and targetEndPoint: 0.0999972
Distance between start and actualEndPoint: 0.0440546
findNearestPoly found a point-in-poly that is 0 meters away from desired point
moveAlongSurface reports actualEndPoint in polygon 188
findNearestPoly reports actualEndPoint in polygon 166
Uh oh, we just moved between two different connected components
```

# What's going on?
The root cause of this issue seems to be that the point returned by `moveAlongSurface` is on the edge shared between 188 and 166.  This point has a distance of 0.0 to 166 and 188 and `dtFindNearestPolyQuery` breaks this tie by returning the polygon found first (166 in this case).

# Possible fix

I haven't tested this thoroughly enough, nor do I full understand `moveAlongSurface` (so this may have a side-effect that I am not aware of), but one possible fix is to take inspiration from the [method of interior-points](https://en.wikipedia.org/wiki/Interior-point_method) and never return a point that is on the edge of a polygon (always stay in the interior of a polygon).

I believe this can be done by after the `dtVlerp` at [DetourNavMeshQuery.cpp#L2188](https://github.com/recastnavigation/recastnavigation/blob/master/Detour/Source/DetourNavMeshQuery.cpp#L2188), adding something like `dtVlerp(bestPos, curPolyCenter, bestPos, 1.0 - 1e-5)` as that'll move the point just barely off the edge and into the interior of the current polygon.

P.S. The mesh in question is part of the [Matterport3D dataset](https://niessner.github.io/Matterport/), and, according to the license, I can't provide a public link to the source mesh.  If you'd like the source mesh, DM me.

**Comment by memononen** [comment]
This is expected behavior, `findNearestPoly()` "teleports" to the nearest location, it does not have knowledge of prior path. You should call it only when the agent needs to be reset back to the navmesh. If you want to keep agent on the detail mesh after movement, then use `getPolyHeight()` to adjust the height.

Since floating points are only so accurate, the polygon refs and topology are more important 3D points, and are in general favoured to solve problems you just encountered.

Summa summarum, without knowing your use case, the use of `findNearestPoly()` in the end is most likely the correct solution to what you are trying to accomplish.

**Comment by erikwijmans** [comment]
I believe the bug is in `moveAlongSurface` not `findNearestPoly`.  It definitely seems wrong for `moveAlongSurface` to return a point that is in a different connected component according to `findNearestPoly`.

**Comment by memononen** [comment]
`findNearestPoly` cannot be used to check the correctness or end result of `moveAlongSurface` since find nearest "teleports", and move along surface is constrained to topology. Apples and oranges.

What are you trying to accomplish with your test?

**Comment by erikwijmans** [comment]
We are building a simulator for training virtual robots for various navigation tasks. When the robot attempts to move forward in its environment, we first calculate the end location using its current hearing and step size. Then, in order to provide movement that respects the topology of the simulated environment, we use `moveAlongSurface` between the current location and calculated end location to get the actual end location. 

We really only care about its location in 3D space, so we haven’t been tracking which polygon it is currently in and use `findNearestPoly` to look it up whenever that is needed. For various reasons (multi agent support, support of querying the shortest path distance from the current location or from an arbitrary 3D point to an arbitrary 3D point), it isn’t easy or necessarily feasible for us to start tracking that.

**Comment by memononen** [comment]
Ok, now I understand your use case.

For good results, the agents should have a 3D locator, which is a Vec3 + PolyRef. You try to remap the locator (findNearestPoly) only when absolutely necessary, i.e. placing the agent, teleporting the agent, or when the current poly becomes invalid.

After years of banging my head against the wall, that is the only reasonably robust way to do it. Your system design might be different, but this the way Recast/Detour assumes the usage.

In the projects where I've used R&D, tracking the poly has never been an issue (we've often wrapped it into a Locator3D class/struct), but in many cases it has taken some mind juggling to accept the idea that topology is more important than the 3D location :)
