### ISSUE TITLE
How to get obstacle distance

### ISSUE THREAD

**Issue by acrushdjn** [recastnavigation/recastnavigation#378]
Hi,

Is there a way to get obstacle distance for certain point?
Say for one point (x, y, z) and one direction _d_, if I walk from this point (x, y, z) in the direction of _d_, just go straight, never take any turns, what is the maximum distance can I walk before touching any obstacles, is there a way to get this information?

**Comment by jakobbotsch** [comment]
You can use the [`dtNavMeshQuery::raycast`](https://github.com/recastnavigation/recastnavigation/blob/14b2631527c4792e95b2c78ebfa8ac4cd3413363/Detour/Source/DetourNavMeshQuery.cpp#L2444-L2484) method for this task.

Note that the ray will stay constrained to the nav mesh so this is not a 3D raycast. For example, it will "walk down" ramps.
