### ISSUE TITLE
 How to dynamically refresh partial mesh?

### ISSUE THREAD

**Issue by Iraas** [recastnavigation/recastnavigation#382]
Hi,I have a problem. If a new obstacle suddenly appears in the game, the original mesh will no longer work. It is too inefficient to refresh all the mesh at runtime, so is there any way to refresh the partial mesh at runtime?

**Comment by jakobbotsch** [comment]
You can use the tile cache to do this efficiently. See the "Temp Obstacles" sample in the demo.
