### ISSUE TITLE
How to judge whether a point is an obstacle？

### ISSUE THREAD

**Issue by yaoraoto** [recastnavigation/recastnavigation#384]
Give a coordinate point at random, how to judge whether the point is in the obstacle or not？

**Comment by jakobbotsch** [comment]
You can use `dtNavMeshQuery::findNearestPoly` to check whether there is a poly at the point. If there isn't, then it is an unmeshed area.

**Comment by monitor1394** [comment]
I want to ask the same question

![image](https://user-images.githubusercontent.com/1450329/60802917-9bb09a80-a1ac-11e9-9c89-355b93713f06.png)

as shown in the picture
I want the start point return false when use dtNavMeshQuery::findNearestPoly, but now it is return true.

What else do I need to add?

**Comment by SpangMcgraw** [comment]
Find nearest poly done with very small extents in this situation should
return a poly ref of zero, if your extents are to big it will return a poly
that lies within them.
