### ISSUE TITLE
Can addObstacle improved to be more effecient?

### ISSUE THREAD

**Issue by phyhwj** [recastnavigation/recastnavigation#390]
I need to use recastnavigation in my game server,  I test the method addObstacle cost average 7ms to recast tile mesh in release O2 version, but I expected 100 battles on my server at the same time. Is there anyway to improve it? Thank You.

**Comment by MINIONBOTS** [comment]
I guess addObstalce is not your problem, but the update -> buildNavMeshTile(..) is the slowpoke ? Did you test which function is the cause of it ? 
I would say it is the rebuilding of the mesh tile(s), that is the slowest part in this process. You can try to lower the TileSize, that should speed things up.

**Comment by phyhwj** [comment]
> I guess addObstalce is not your problem, but the update -> buildNavMeshTile(..) is the slowpoke ? Did you test which function is the cause of it ?
> I would say it is the rebuilding of the mesh tile(s), that is the slowest part in this process. You can try to lower the TileSize, that should speed things up.

Thanks Your Reply. 
Yes, I mean that it costs most in buildNavMeshTile. I test it in default tile size 48x48 and using cell size 0.17. I will try to lower the tile size. Whether it would increase cost in other method like find Path？

**Comment by MINIONBOTS** [comment]
I don't know how the cell size relates to whatever you are doing, but if you increase the cellsize, that should also speed things up a bit.

**Comment by phyhwj** [comment]
> I don't know how the cell size relates to whatever you are doing, but if you increase the cellsize, that should also speed things up a bit.
> A smaller tilesize should not really affect findpath, the effect of smaller polygons in some places should be nearly zero when it comes to pathfinding.

Ok, I will try it. Thank You.
