### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by alexzk1** [recastnavigation/recastnavigation#392]
Not sure if I have too big map, or something went wrong trying to fix another bugs, but:

RecastContour.cpp:483:26: runtime error: signed integer overflow: 466743685 * 466744550 cannot be represented in type 'int'
RecasttMesh.cpp:396:34: runtime error: signed integer overflow: 466743717 * 466743717 cannot be represented in type 'int'

Last one got silenced moving to init64_t 4 variables there.

**Comment by grahamboree** [comment]
Hi.  Sounds like your input geometry is quite large and/or you're not using tiled meshes.  If this is still a problem and you have a specific repro case, please open a new issue and include repro steps.  Thanks.
