### ISSUE TITLE
Any idea why ?

### ISSUE THREAD

**Issue by alexzk1** [recastnavigation/recastnavigation#395]
I'm confused. Any idea why recast did that ? (part of mesh went to very bottom).

![image](https://user-images.githubusercontent.com/4589845/58638291-22946c80-82fd-11e9-8cc2-8629ccfb3cfb.png)

**Comment by jakobbotsch** [comment]
This can happen if you have a very tall bounding box. You can try to increase the number of bits for span heights to 16 (the max value):
https://github.com/recastnavigation/recastnavigation/blob/c40188c796f089f89a42e0b939d934178dbcfc5c/Recast/Include/Recast.h#L266
Or you can see if you can use a shorter bounding box.

**Comment by alexzk1** [comment]
Right, I increased voxel per 1 world unit amount .... it was10 and it was bad shape, so I did 30. Could be that. Let me try to decrease to 15-20 voxels.

**Comment by alexzk1** [comment]
Btw, why you said 16 is max? Fields are

```
public:
unsigned int smin :
    RC_SPAN_HEIGHT_BITS; ///< The lower limit of the span. [Limit: < #smax]
unsigned int smax :
    RC_SPAN_HEIGHT_BITS; ///< The upper limit of the span. [Limit: <= #RC_SPAN_MAX_HEIGHT]
    unsigned int area : 6;                   ///< The area id assigned to the span.
    rcSpanPtr next;                            ///< The next span higher up in column.
};
```
So 13 was max, otherwise it goes over 32 bits. And can use 24 bits (not 16) as well, since next is int 64

**Comment by alexzk1** [comment]
Any way, thanks. Lowered  .walkableHeight = 20; (down from 30) and set 16 bits, mesh is back whole.

**Comment by jakobbotsch** [comment]
These coordinates are stored and saved as 16-bit ints in further stages of the build process and also in the final mesh. Normal meshing processes will have millions of `rcSpan` so increasing its size will also affect RAM usage by a lot.

**Comment by alexzk1** [comment]
Yes, RAM consuming is important, but can be saved just buying extra 16Gb for 30$ on build server. However, bit manipulations take many of time actually, bit fields are not recommended to be used at least on Intels long ago.

**Comment by jakobbotsch** [comment]
You are free to do those things. Other people have different use cases and cannot prebuild their meshes.
