### ISSUE TITLE
delaunayHull

### ISSUE THREAD

**Issue by alexzk1** [recastnavigation/recastnavigation#396]
I added 
 assert(nfaces);

before

// Create tris

inside function 
static void delaunayHull 

because I had wrong indexes around ... sooo, any idea why nfaces == 0 happen and what to do with that ?
I have a lot maps and it happens sometime, i.e. most of them it do ok.

At least, how to handle that ? Skip to next in loop, or skip that polygon...cant decide.

**Comment by alexzk1** [comment]
![image](https://user-images.githubusercontent.com/4589845/58768613-b9378680-85a6-11e9-98a7-a009715e0e19.png)

This is how polymesh looks, and detail mesh fails there with nfaces = 0

**Comment by alexzk1** [comment]
Okey, tried 2 versions:
simple:
```
if (nfaces == 0)
  nfaces = 1;

```
And harder:
```
 const auto ensure_tris_size = [&tris](int en)
    {
        const int sz = en * 4 + 4;
        if (tris.size() < sz)
            tris.resize(sz, -1);
    };

    for (int i = 0; i < nedges; ++i)
    {
        const int* e = properties::Ptr(edges, i * 4, 4);
        if (e[3] >= 0)
        {
            // Left face

Both give next final navigation mesh with that HUGE going up pylon:
![image](https://user-images.githubusercontent.com/4589845/58768788-0e749780-85a9-11e9-9e29-ac3cc11dba5f.png)

            ensure_tris_size(e[3]);
```

**Comment by alexzk1** [comment]
Ok...tried to exit function with nfaces ==0, and keep old tris for next loop iteration, like that:
```
// Create new triangulation.
            // TODO: Incremental add instead of full rebuild.
            rcIntArray tmptris;
            delaunayHull(ctx, verts, hull, tmptris);
            if (!tmptris.empty())
                std::swap(tmptris, tris);
```

Still the same picture with "pylons" ... maybe something else is broken.

**Comment by grahamboree** [comment]
It sounds like your input geometry needs to be sanitized before it's passed to Recast.  If there are incorrect indexes, degenerate triangles, or other similar problems it will create a cascade of issues in Recast's output.  If you have a specific problem with a repro case using valid geometry, please open a new issue for that specifically.
