### ISSUE TITLE
compiling error 'premake5.lua:18: attempt to call global 'symbols' (a nil value)'

### ISSUE THREAD

**Issue by Siqi-Wang47** [recastnavigation/recastnavigation#401]
Hi all,

Anyone knows what does the error: 
'recastnavigation/RecastDemo/premake5.lua:18: attempt to call global 'symbols' (a nil value)' mean? It occurs when I try to run 'premake5 gmake' from the RecastDemo folder.

Thanks in advance!

**Comment by ndeshp2s** [comment]
Hi @Siqi-Wang47,

I could get rid of this error by adding an "=" sign at the lines where it occurred. 
For instance,  symbols "On" at line number 18 becomes symbols = "On".
