### ISSUE TITLE
Unable to compile on ubuntu 18.04

### ISSUE THREAD

**Issue by ndeshp2s** [recastnavigation/recastnavigation#403]
Hello,

I am trying to build the RecastDemo on Ubuntu 18.04. However, I get the following error when I run make in Build/gmake:
`==== Building DebugUtils (debug) ====
==== Building Detour (debug) ====
DetourAlloc.cpp
cc1plus: error: -Werror=class-memaccess: no option -Wclass-memaccess
Detour.make:133: recipe for target 'obj/Debug/Detour/DetourAlloc.o' failed
make[1]: *** [obj/Debug/Detour/DetourAlloc.o] Error 1
Makefile:46: recipe for target 'Detour' failed
make: *** [Detour] Error 2`

How can solve this issue?

Thankyou in advance.

**Comment by aurthes6220** [comment]
I have met the same situation. I need someone's help too.

**Comment by Dig-Doug** [comment]
As a temporary workaround, I was able to build by removing the compiler flag:

```bash
cd RecastDemo
sed -i -e 's/-Wno-error=class-memaccess//g' premake5.lua
# Run premake, etc.
```
