### ISSUE TITLE
Does the agent support auto jump?

### ISSUE THREAD

**Issue by 1201yuge** [recastnavigation/recastnavigation#408]
If the character wants to jump from one isolated area to another, can the jump route be generated automatically without adding jump link manually?

**Comment by Bromeon** [comment]
With "jump", you mean an off-mesh connection?

If you don't add those connections, how would Recast/Detour know which jumps are valid and which aren't?

**Comment by 1201yuge** [comment]
Oh, I'm sorry. Maybe I didn't make it clear. I mean whether the function of automatically generating off-mesh connections is supported, just like in unity.
