### ISSUE TITLE
Feature Request - Path multiple navmesh.

### ISSUE THREAD

**Issue by BluePrintRandom** [recastnavigation/recastnavigation#412]
in a project of my own I found some optimizations in py to make A* much faster.

we break up the world navmesh into many small navmeshes

each navmesh knows what navmeshes it's connected to

we can do

is start / end on same 'chunk' -> just pathfind chunk
if fail pathfind all adjacent chunks + original chunk

is start / end on tiles that are connected path find just the two tiles
if that fails pathfind all tiles adjacent to both tiles

else pathfind using Chunks -> build a navgraph that is just those chunks -> pathfind that.

I was able to pathfind a whole planet in py in short order

another optimization is to store the graphs name sorted 
so we can use the same graph from either end etc.

ie 

graphs

[ 6 , 2, 1 ]

is stored as

[1, 2, 6]

**Comment by Bromeon** [comment]
What you describe is known as _Hierarchical Pathfinding_ and a common approach to counter scalability problems of a pure nav-mesh based search.

While it is certainly a useful feature, I'm not sure if Recast&Detour (which is rather low-level) is the right place for it, or if such additions could be done on top of Recast&Detour (potentially using other libraries). If you think it belongs here, it might be worth discussing different approaches more concretely.

You should also check out [this blogpost](https://digestingduck.blogspot.com/2010/03/sketch-for-hierarchical-pathfinding.html) of Mikko Mononen (Recast&Detour's original author). One approach it suggests is using _tiles_ as an abstraction.

**Comment by grahamboree** [comment]
Consolidated hierarchical pathfinding feature into #640
