### ISSUE TITLE
RecastDemo doesn't build

### ISSUE THREAD

**Issue by jdestefx** [recastnavigation/recastnavigation#413]
Centos 7.6

[root@GD-4105-SVR gmake]# make
==== Building DebugUtils (debug) ====
Creating obj/Debug/DebugUtils
DebugDraw.cpp
DetourDebugDraw.cpp
RecastDebugDraw.cpp
RecastDump.cpp
Creating lib/Debug
Linking DebugUtils
==== Building Detour (debug) ====
Creating obj/Debug/Detour
DetourAlloc.cpp
cc1plus: error: -Werror=class-memaccess: no option -Wclass-memaccess
make[1]: *** [obj/Debug/Detour/DetourAlloc.o] Error 1
make: *** [Detour] Error 2

**Comment by ash1215** [comment]
I got the same error in Ubuntu 18.04
Though deleting the code " -Wno-error=class-memaccess " from Detour.make helped me solve this error. But I don't know if deleting is a good idea. Anyone has any other solution, please let me know.
