### ISSUE TITLE
findNearestPoly fails to find anything despite being very close to the navmesh 

### ISSUE THREAD

**Issue by TheSHEEEP** [recastnavigation/recastnavigation#416]
I am implementing recast/detour in a module of mine and have now reached the point of adding agents and giving them move targets.

If adding the agent (and setting the move target) works, everything works just fine.

However, agents in some positions simply cannot be added. I dug into the code and the reason for that is that findNearestPoly is unable to find something usable, thus the agents receive an invalid state upon adding.  
Similarly, when trying to set a movement target by using findNearestPoly, it will work in some places and not in others.

This would be understandable if I tried to place agents in very remote faraway locations, but that is not the case. The normal extents are about (1/1/1) and the agents are about 0.0-0.2 points away from the navmesh, so this should never be a problem.

Here's an image of the situation (red X = couldn't be added):
![xV1trSZ](https://user-images.githubusercontent.com/1766205/71586763-f86d8c00-2b23-11ea-85bb-70cf36b8a469.png)
As you can see, all the agents have the same distance to the ground, there's absolutely no difference in their Y-position.
The visible tiles come directly from the detour debug drawing function so they are not faulty, either (and can be traversed just fine by agents that were successfully added).

It also seems to be the case that the closer the agents are to the corner vertices of the tiles, the more likely they are to be successfully added.

I also noticed that when I manually increase the extents used in findNearestPoly to much larger values, it seems to work reliably everywhere, adding every agent to the position they should be at.

Now I could of course just use extreme extent values everywhere, but I'd rather get this fixed.

Besides, you cannot externally set the extents used by dtCrowd when adding an agent. They are just automatically set to 0.5x max agent radius and can never be changed (this should be made accessible, btw.).
So I would have to change detour sources themselves, which I would very much like to avoid to be able to just have it as a git submodule.

**Comment by TheSHEEEP** [comment]
This is my project, in case someone wants to look at how I am adding agents/setting movement targets:
https://github.com/TheSHEEEP/godotdetour

**Comment by memononen** [comment]
When it finds a polygon, is it correct one? Easy way is to debug draw that
too.

Usually these are because of coordinate system conversions.


--mikko

**Comment by TheSHEEEP** [comment]
As I wrote, when it does work and the agents are added correctly (like the two in the screenshot), everything works fine.

I can set a move target and copy the agent's values over to the game objects regularly - and there's no teleporting around happening at the start, so the agents really are where they should be - the same place the game objects are.

I don't really think this is a conversion problem as everything else, adding temporary obstacles, marking areas as water/grass/etc., rebuilding specific tiles at runtime (selected by position), etc. all works perfectly fine.

The only thing not really working seems to be findNearestPoly.

**Comment by TheSHEEEP** [comment]
> When it finds a polygon, is it correct one? Easy way is to debug draw that too.

Some more information, I actually printed the vertices of the polygon compared to the position I was checking:

> *********** target pos: (-16.242544, 0.099999, 14.486492)
> *********** Poly vertex: -19.4 0.13915 11.5
> *********** Poly vertex: -19.4 0.13915 17.799999
> *********** Poly vertex: -13.7 0.13915 17.799999
> *********** Poly vertex: -13.7 0.13915 11.5
> 
> *********** target pos: (-16.975807, 0.1, -16.747889)
> *********** Poly vertex: -19.4 0.13915 -19.4
> *********** Poly vertex: -19.4 0.13915 -13.7
> *********** Poly vertex: -13.7 0.13915 -13.7
> *********** Poly vertex: -13.7 0.13915 -19.4

The first one of these could only be found by increasing the extents (not sure by how much, but the default was not enough).  
The second one could be found without increasing the extents.

Both definitely seem to be the correct polygon, given that the target position lies within them.  
So... yes, really quite sure this is not a coordinate system conversion problem.  
But still no clue what the actual problem could be.

**Comment by memononen** [comment]
Can you dump the values you pass to findNearestPoly() on successful and
failed case?

Just to make sure, is Godot using the same coordinate system as Recast?

**Comment by TheSHEEEP** [comment]
Godot uses Y-up and Z-forward axis.

The values in the successful case (touched tiles are a print of the min/max x&y inside dtNavMeshQuery::queryPolygons, line 920):

Working case:
> pos: -16.169159 -0.1 -15.39929  extents: 1 0.75 1
> Touched tiles: x: 0/0 y: 0/1

Non-working case:
> pos: -16.518005 -0.1 13.567456  extents: 1 0.75 1
> Touched tiles: x: 0/0 y: 7/8

**Comment by TheSHEEEP** [comment]
And here is some more information.  
I narrowed down where things begin to differ from successful to failing case.  
In this code ( dtNavMeshQuery::queryPolygons ):
```
for (int y = miny; y <= maxy; ++y)
	{
		for (int x = minx; x <= maxx; ++x)
		{
			const int nneis = m_nav->getTilesAt(x,y,neis,MAX_NEIS);
			for (int j = 0; j < nneis; ++j)
			{
				queryPolygonsInTile(neis[j], bmin, bmax, filter, query);
			}
		}
	}
```

In the working case, nneis is not 0.  
In the failing case, nneis is 0.

Unfortunately, this is getting pretty deep into recast internals and my understand of what this actually means is pretty low.

**Comment by memononen** [comment]
Sound like it's coordinate system problem after all. Recast uses the same
coordinate system as OpenGL, up=Y, forward=-Z. The changes are that some
winding calculations get wrong because of that.

--mikko

**Comment by TheSHEEEP** [comment]
> Sound like it's coordinate system problem after all. Recast uses the same coordinate system as OpenGL, up=Y, forward=-Z. The changes are that some winding calculations get wrong because of that.

That is exactly the same as Godot.
Sorry, I did mean to say -Z is forward in Godot (same as in OpenGL).

**Comment by memononen** [comment]
I'm pretty sure your bug is this:
https://github.com/TheSHEEEP/godotdetour/blob/master/src/detournavigationmesh.cpp#L190

Happy New Year!

**Comment by TheSHEEEP** [comment]
lol.
Are you telling me tileHeight is actually the tile's "depth", so the Z axis in 3D?
But because tiles are 2D (kinda), it is named "height"?

In the same way that tiles have an X and an Y, instead of an X and a Z?

**Comment by TheSHEEEP** [comment]
Oh, boy.
Yes, that fixed it.

So, to sum it up:
Please don't call your depth "height" just because it is in 2-dimensional.
Something called height should be the same axis across the 2D and 3D space or it will confuse the hell out of people.

Well, I'm just glad that resolved the problem.
Thanks for helping, I don't think I could've found that one myself this fast.
Happy New Year!
