### ISSUE TITLE
 I want to use TileMesh on a server.

### ISSUE THREAD

**Issue by ssaturn** [recastnavigation/recastnavigation#419]
I want to insert obstacles using a tile mesh.
It takes about 1 second to load the map.
Since there are various maps, it is difficult to load and hold all the maps.

I am currently loading all maps and using them as constable when running the server with SoloMesh (without obstacles).
If I use TileMesh to insert obstacles to insert it, you will need to make it constant as above to prevent reuse. You may need to load the map dynamically, but it takes a long time to load the map.

Is there a better way?

**Comment by grahamboree** [comment]
I'm not following exactly, but in general you want to use TileMesh when the world you're loading is large or frequently updated.  It sounds like you have a lot of navigation data so you may also want to revisit your navmesh generation settings to confirm you're not generating excessively detailed navigation data.
