### ISSUE TITLE
when i addObstacle with a big radius There seems to be something wrong

### ISSUE THREAD

**Issue by rehen** [recastnavigation/recastnavigation#420]
i try to add an Obstacle with a big radius (15.0f) then I got a response as shown in illustration
how can i fix it?
![quest](https://user-images.githubusercontent.com/17619099/74802489-01552f80-5315-11ea-8839-3587681b0de8.png)

**Comment by grahamboree** [comment]
Temporary obstacles are meant to cover small areas.  For large obstacles, especially ones that span multiple tile boundaries you'll want to instead regenerate those tiles and incorporate the obstacle mesh as un-walkable input geometry.
