### ISSUE TITLE
How can I get the path considering the agent size?

### ISSUE THREAD

**Issue by oneig79** [recastnavigation/recastnavigation#423]
![image](https://user-images.githubusercontent.com/61779333/75862848-e1f4f100-5e42-11ea-9baa-9b9ce6d5bb58.png)

**Comment by grahamboree** [comment]
Hi.  Navmeshes built such that they take into account the agent radius and agents navigate as a point mass.  When you build a navmesh you should set `walkableRadius` in your `rcConfig` instance to the radius of the agent.
