### ISSUE TITLE
a code optimization in RecastFilter

### ISSUE THREAD

**Issue by pirunxi** [recastnavigation/recastnavigation#427]
relate code at Recast/Source/RecastFilter.cpp ,line range: 134 - 141 and 186 - 189

code at line 139:
minh = rcMin(minh, -walkableClimb - bot);

and at line 186:
	if (minh < -walkableClimb)
	{
		s->area = RC_NULL_AREA;
	}

we know (- walkableClimb - bot) must less than -walkableClimb, we can break current for loop because we can sure the if condition at line 186 is true.

**Comment by jackpoz** [comment]
I would suggest to open a Pull Request with your suggested changes

**Comment by grahamboree** [comment]
Thanks!  Please open a PR with this change and we can discuss it further there.
