### ISSUE TITLE
Installation on Ubuntu 18

### ISSUE THREAD

**Issue by Abanoub-G** [recastnavigation/recastnavigation#431]
Hi All, 
This is just a reminder for myself and my colleague @medusa606 (if we ever need to do this again) of how to install recastnavigation on our machines and hopefully will benefit others in the community. 

1) Clone repository recastnavigation

2) Install SDL2 by running: sudo apt-get install libsdl2-dev

(ref: https://lazyfoo.net/tutorials/SDL/01_hello_SDL/linux/index.php)

3) Get premake 5 for linux from https://premake.github.io/download.html#v5 

4) Extract premake5 zip and move premake5 to RecastDemo folder in recastnavigation

5) In RecastDemo, run in terminal: ./premake5 gmake

6) Then go to Build/gmake  and run: make

7) If you get “error: -Werror=class-memaccess: no option -Wclass-memaccess”  then search/grep the makefiles for “Werror=class” 
  7.1) run: grep -rliI "memaccess" 
  7.2) Go through each of the files and delete the flags (should be in RecastDemo.make and Detour.make) 
  7.3) In RecastDemo run:  sed -i -e 's/-Wno-error=class-memaccess//g' premake5.lua
  7.4) Go back to step 5)

8) Run RecastDemo\Bin\RecastDemo

Hope this helps others as well.

**Comment by jakobbotsch** [comment]
I fixed your 7th point in #432. The rest seems to be covered by the readme.
