### ISSUE TITLE
False-positive Out-of-memory prints in rcBuildHeightfieldLayers()

### ISSUE THREAD

**Issue by unvestigate** [recastnavigation/recastnavigation#433]
Hey folks,

I am build a multi-tile navmesh using a modified version of the code from Sample_TempObstacles.cpp. In general it works really well. However, I get "rcBuildHeightfieldLayers: Out of memory 'regs' (0)." error prints when feeding the system navmeshes with a lot of steep cliffs.

After some brief debugging it seems to me that the nregs variable on line 222 in RecastLayers.cpp is zero, in other words it attempts to allocate zero elements which gives the error. In practice this does not seem to be a problem since rasterizeTileLayers() (also from the sample) returns zero in this case and the tile is simply skipped. However, the error is a bit annoying.

If I feed the system a relatively simple scene, eg. a flat plane with a few boxes, I don't get the errors which suggests it has something to do with with the slopes and curves of the navmesh. Everything seems to work fine at runtime though, with or without a "problematic" scene.

So my questions are: Should we perhaps add a check to rcBuildHeightfieldLayers() to silently early-out if there are no regions to build? Am I actually looking at this wrong? Ie. should I indeed be worried about the errors, and instead try to resolve the issues by adjusting parameters or the geometry?

Thanks!

**Comment by grahamboree** [comment]
The issue is related to the specific inputs to `rcBuildHeightfieldLayers`.  Seems like either the compact heightfield size is 0 in one dimension or the border region is larger than one of the dimensions.
