### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by psi29a** [recastnavigation/recastnavigation#434]
Hello!  We've been using recastnavigation in OpenMW for awhile now, but have added it as an external dependency due to the fact that there hasn't been any 'releases' for awhile.

Releases are kind of important, because I can take that and create packages. As a Debian developer, I can get it into Debian and Ubuntu. I've already created the Intent to Package (ITP) bug, but all I'm waiting on to continue is a recent release... will there be on in the near future? :D

**Comment by DarthGandalf** [comment]
FTR, for Gentoo I packaged recastnavigation from the git snapshot from 11 May, with #437 applied, because of the OpenMW dependency.

Would appreciate a proper release.

**Comment by psi29a** [comment]
Yeah... :D
I need a proper release to work through the ITP on Debian/Ubuntu.

**Comment by psi29a** [comment]
Pretty please? :)

**Comment by DarthGandalf** [comment]
https://github.com/recastnavigation/recastnavigation/releases/tag/v1.6.0 appeared 3 days ago

**Comment by grahamboree** [comment]
Thanks @DarthGandalf!  Apologies it took this long to get a 1.6 out 😅
