### ISSUE TITLE
build sole mesh failed, use a 4800x4800 obj file.

### ISSUE THREAD

**Issue by sniper00** [recastnavigation/recastnavigation#435]
obj file content:
```
g default
v 0 0 0
v 0 0 -4800
v 4800 0 -4800
v 4800 0 0

vn 0 -1 0
vn 0 -1 0
vn 0 -1 0
vn 0 -1 0

vt 0 0
vt 0 0
vt 0 0
vt 0 0

usemtl None
usemap None

f 3/3/3 2/2/2 1/1/1
f 1/1/1 4/4/4 3/3/3
```

**Comment by grahamboree** [comment]
For a plane this large, it's best to split up generation into chunks with the tile mesh generator and pay close attention to the build parameters used, as they can have a massive impact on performance.
