### ISSUE TITLE
cmake policy warning about glvnd (trunk build)

### ISSUE THREAD

**Issue by LW-archlinux** [recastnavigation/recastnavigation#441]
> CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindOpenGL.cmake:305 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
FindOpenGL found both a legacy GL library:
    OPENGL_gl_LIBRARY: /usr/lib/libGL.so
  and GLVND libraries for OpenGL and GLX:
    OPENGL_opengl_LIBRARY: /usr/lib/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/libGLX.so
  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  RecastDemo/CMakeLists.txt:9 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

I doubt recastnavigation cares whether glvnd is used, but many linux distros do.
See https://cmake.org/cmake/help/latest/policy/CMP0072.html for possible solutions

**Comment by elsid** [comment]
Could you just specify `OpenGL_GL_PREFERENCE` when build recastnavigation? Mentioned policy allows CMake to choose which one is default but if your requirements are different from the default you must specify the variable when running CMake.
