### ISSUE TITLE
Compilation error, gcc 10.2

### ISSUE THREAD

**Issue by Arsakes** [recastnavigation/recastnavigation#446]
Archlinux GCC 10.2:
RecastDuring demo compliation:

```
../../Source/TestCase.cpp: In member function ‘bool TestCase::load(const string&)’:
../../Source/TestCase.cpp:158:32: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct TestCase::Test’ with no trivial copy-assignment; use value-initialization instead [-Werror=class-memaccess]
  158 |    memset(test, 0, sizeof(Test));
      |                                ^
In file included from ../../Source/TestCase.cpp:23:
../../Include/TestCase.h:33:9: note: ‘struct TestCase::Test’ declared here
   33 |  struct Test
      |         ^~~~
../../Source/TestCase.cpp:172:32: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct TestCase::Test’ with no trivial copy-assignment; use value-initialization instead [-Werror=class-memaccess]
  172 |    memset(test, 0, sizeof(Test));
      |                                ^
In file included from ../../Source/TestCase.cpp:23:
../../Include/TestCase.h:33:9: note: ‘struct TestCase::Test’ declared here
   33 |  struct Test
      |         ^~~~
cc1plus: all warnings being treated as errors
```

EDIT: Because I'm an absolute moron when it comes to C++ and i simply deleted the offending `memset` lines and thing worked.

**Comment by footman136** [comment]
If you met the "memset not defined" error, you should add "include <string.h>"in Sample.cpp, SampleInterface.cpp, and change "include <string>" to "include <string.h>" in main.cpp. The error is not related with "Test", but "memset". Because "memeset" is defined in Windef.h in Windows platform, but in <string.h> in Linux platform.

**Comment by Bromeon** [comment]
Those are usually warnings, as the line `cc1plus: all warnings being treated as errors` suggests.
Removing arbitrary lines of code to "fix" warnings is definitely a bad idea.

But the warnings already recommend a potential fix: using value initialization, i.e. `Test test = {};`.

@footman136 the errors are not about undefined `memset`, and even in that case, the correct header would be `<cstring>`, and it's the same one on all operating systems. See https://en.cppreference.com/w/cpp/string/byte/memset -- `<string.h>` is a C header.
