### ISSUE TITLE
CMake build of RecastDemo does not work with Visual Studio

### ISSUE THREAD

**Issue by blackmanos** [recastnavigation/recastnavigation#453]
Hi, on Win10, after clicking on RecastDemo.exe the window appears and immediately disappears, the program itself does not start. Tried running as administrator and in compatibility mode, nothing helped. How do I fix the program launch?

**Comment by Bromeon** [comment]
Could it be that some external files cannot be loaded due to wrong working directory?

Start the demo from a command line and see if there is any log output.

**Comment by blackmanos** [comment]
F:\recastnavigation\RecastDemo\Debug>RecastDemo.exe
Launched, no errors are displayed, the program window appears and immediately disappears
What other external files might need?

**Comment by Bromeon** [comment]
Did you build it on that machine?
If you built it with an IDE (e.g. Visual Studio), can you try launching it from the IDE?

**Comment by blackmanos** [comment]
Yes, I builded it on this computer.
Can't start from the Visual Studio.

I followed these steps:
Launched Cmake and generated files for compilation
opened RecastNavigation.sln and build the project
copied SDL2.dll from RecastDemo folder to RecastDemo.exe folder
I run RecastDemo.exe, the window flickers and disappears

**Comment by jakobbotsch** [comment]
Can you try with `premake5` instead (following the instructions in the readme)?

**Comment by blackmanos** [comment]
oh, thanks very much , it happened to run, it turns out that the assembly via cmake was not done correctly ((

**Comment by jakobbotsch** [comment]
Great! I edited the title to reflect that it's the CMake build that's the issue.

**Comment by blackmanos** [comment]
I found why it did not start when compiling via cmake, there was not enough file in the directory DroidSans.ttf

**Comment by jakobbotsch** [comment]
Yes, that file is needed. Do you want to submit a PR to fix the CMake build?

**Comment by blackmanos** [comment]
#454

**Comment by jakobbotsch** [comment]
Fixed by #454
