### ISSUE TITLE
is there any interface available for avoidance priority? for example : human avoid cars but cars wont avoid human?

### ISSUE THREAD

**Issue by powof2** [recastnavigation/recastnavigation#461]
Hi everyone,
I'm wondering is there any interface or method availabe for avoidance priority? here is the use case:
 - human avoid cars and tanks
 - cars avoid tanks
 - tanks avoid nothing

thank you.

**Comment by UltraEngine** [comment]
I did this by creating separate navigation meshes. The big guy gets copied to the small guy's navmesh as an obstacle, so the little guys always navigate around the big monster.
