### ISSUE TITLE
cmake: Install pkg-config definitions

### ISSUE THREAD

**Issue by glebm** [recastnavigation/recastnavigation#472]
Recast CMake install currently does not install pkgconfig definitions. It'd be nice if it did.

Example from another project:

https://github.com/kcat/openal-soft/blob/master/openal.pc.in

https://github.com/kcat/openal-soft/blob/28aaaab434d1b73eb794d593eff368815cb8b3ce/CMakeLists.txt#L1194-L1197

https://github.com/kcat/openal-soft/blob/28aaaab434d1b73eb794d593eff368815cb8b3ce/CMakeLists.txt#L1388-L1389

**Comment by psi29a** [comment]
I'll look into this as I'm already taking care of Debian/Ubuntu packages with the ITP bug.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913828

I also made a FindRecastNavigation.cmake which is a stop-gap solution that others can use. It is BSD 3-clause.
https://gitlab.com/OpenMW/openmw/-/merge_requests/617

**Comment by elsid** [comment]
This is fixed by https://github.com/recastnavigation/recastnavigation/pull/474 and probably should be closed.
