### ISSUE TITLE
Off-mesh connections not working when ends are far apart

### ISSUE THREAD

**Issue by TheSHEEEP** [recastnavigation/recastnavigation#477]
See the following image:
![pathfinding_problem](https://user-images.githubusercontent.com/1766205/113543688-92f23000-95ef-11eb-9b48-2c01a67fa826.png)

It is very clear that off-mesh connections are only working when the ends are close together.  
I'm certain there is some kind of logic to this behavior.

In the code, I can see that ends are drawn red (i.e. not working) according to this logic:
```
// Check to see if start and end end-points have links.
bool startSet = false;
bool endSet = false;
for (unsigned int k = p->firstLink; k != DT_NULL_LINK; k = tile->links[k].next)
{
	if (tile->links[k].edge == 0)
		startSet = true;
	if (tile->links[k].edge == 1)
		endSet = true;
}
```
How these "links" are set when the tile mesh is built, though, I fail to understand, as that is a bit too in-depth in the code for me to get behind at this moment.

What's more important is that I don't see a design reason for this restriction.  
Why not make those connections work from any point to any other point? Why limit the range?

Any explanation or idea to get around this restriction would be very helpful.

**Comment by cybroxtu** [comment]
According to the offmesh-link initialization code in `dtNavMesh::addTile`, only those offmesh-links connecting neighbour tiles are valid.

https://github.com/recastnavigation/recastnavigation/blob/c5cbd53024c8a9d8d097a4371215e3342d2fdc87/Detour/Source/DetourNavMesh.cpp#L1038-L1049

**Comment by TheSHEEEP** [comment]
That seems like a very arbitrary and unnecessary restriction, unless I'm not seeing something here.

**Comment by jakobbotsch** [comment]
I agree, this would be a nice restriction to lift. We need to maintain a table of unlinked offmesh connections to do so to ensure that loading tiles in either order works (that's probably the main reason the restriction is there currently). #195 is related.

**Comment by bmorel** [comment]
Yes, this would be very useful, as it would enable bots to travel through teleporters or to use jumppads (that sends them far away).
