### ISSUE TITLE
How can I see the printf output in RecastDemo

### ISSUE THREAD

**Issue by iclodq** [recastnavigation/recastnavigation#486]
In RecastDemo , there is a Logger, and I used it to print some info,  but sometimes  it don't work, maybe I use it wrong.
And  I hope to use stdio  directly,  Is there a way?

**Comment by zkz196** [comment]
editbin /SUBSYSTEM:CONSOLE $(OUTDIR)\RecastDemo.exe

**Comment by grahamboree** [comment]
Log messages in the build process are saved in an array for displaying later.  https://github.com/recastnavigation/recastnavigation/blob/c5cbd53024c8a9d8d097a4371215e3342d2fdc87/RecastDemo/Source/SampleInterfaces.cpp#L35-L55
you can add a `printf` call there if you want them to dump to stdout during the build process.  This system in RecastDemo is tying into the logging callback in `rcContext` https://github.com/recastnavigation/recastnavigation/blob/c5cbd53024c8a9d8d097a4371215e3342d2fdc87/Recast/Include/Recast.h#L151
