### ISSUE TITLE
findRandomPointAroundCircle always return false when circle is small and poly is large

### ISSUE THREAD

**Issue by huangfeidian** [recastnavigation/recastnavigation#487]
`findRandomPointAroundCircle`   use `dtRandomPointInConvexPoly` to generate a random point in poly, then check the random point is in the circle. But when the poly is large poly and the circle is a small circle ,  like circle radius is 1 while poly is an 10 * 10 grid, the  possibility that the random point generated by `dtRandomPointInConvexPoly` lies in the small circle  is so low that even hundreds of iteration cant return a valid position.

**Comment by MaxHayman** [comment]
Whilst I would prefer it actually return a point in the circle, this is the behaviour defined within 

https://github.com/recastnavigation/recastnavigation/blob/c5cbd53024c8a9d8d097a4371215e3342d2fdc87/Detour/Include/DetourNavMeshQuery.h#L463

**Comment by huangfeidian** [comment]
I narrow down the problem to generate a random point in the intersection area of triangle and circle with in same plane. But so many cases to handle.  [9 cases of intersection of triangle and circle ](https://i.stack.imgur.com/4A8EJ.png)

**Comment by huangfeidian** [comment]
I narrow down the problem to generate a random point in the intersection area of triangle and circle with in same plane. But so many cases to handle.
![4A8EJ](https://user-images.githubusercontent.com/3107971/120302574-9f012200-c300-11eb-95b4-1f9a329b4f10.png)

**Comment by jakobbotsch** [comment]
As you have found it is very non-trivial (and slow) to clip the nav mesh to the input circle before generating the points, hence the function only uses the input circle to restrict which polygons can be selected. So indeed, it is by design that the point returned can lie outside the circle.

**Comment by ppiastucki** [comment]
FYI: I have implemented such a functionality in recast4j by approximating a circle with a dodecagon and using the convex-convex intersection algorithm by O'Rourke (https://github.com/ppiastucki/recast4j/commit/44e4e33562441d25e69e4876f9bffe10b5b3225c). The version which clips polys is roughly 30% slower which is acceptable in my opinion.

**Comment by MaxHayman** [comment]
> FYI: I have implemented such a functionality in recast4j by approximating a circle with a dodecagon and using the convex-convex intersection algorithm by O'Rourke ([ppiastucki/recast4j@44e4e33](https://github.com/ppiastucki/recast4j/commit/44e4e33562441d25e69e4876f9bffe10b5b3225c)). The version which clips polys is roughly 30% slower which is acceptable in my opinion.

That looks interesting! For me performance isn't essential as im wanting to do a one off call to find spawning points around a boss but don't want them spawning in walls or too far away.

**Comment by huangfeidian** [comment]
> FYI: I have implemented such a functionality in recast4j by approximating a circle with a dodecagon and using the convex-convex intersection algorithm by O'Rourke ([ppiastucki/recast4j@44e4e33](https://github.com/ppiastucki/recast4j/commit/44e4e33562441d25e69e4876f9bffe10b5b3225c)). The version which clips polys is roughly 30% slower which is acceptable in my opinion.

for a low requency function, I would value the correct answer than a quick one. Thank you for the solution, I would look into it later.

**Comment by jakobbotsch** [comment]
Very cool! 30% is certainly not bad. If someone were to contribute this functionality I would happily accept it.

> That looks interesting! For me performance isn't essential as im wanting to do a one off call to find spawning points around a boss but don't want them spawning in walls or too far away.

It's pretty common that the circle is large in which case rejection sampling should be ok. Is that not the case here?

**Comment by grahamboree** [comment]
Adapting the new query method addition to #638
