### ISSUE TITLE
MacOS Demo issue

### ISSUE THREAD

**Issue by wuharvey** [recastnavigation/recastnavigation#489]
Hey there! I'm trying to build RecastDemo on MacOS but get an `EXC_BAD_ACCESS` in `imguiRenderGL.cpp`. I've followed the steps in the README.

<img width="862" alt="Screen Shot 2021-07-25 at 8 29 52 PM" src="https://user-images.githubusercontent.com/6209894/126918582-a9b1a784-1fc2-4293-a515-f58d96d00d74.png">

**Comment by CoolDesert** [comment]
maybe SDL_GL_CreateContext  failed

**Comment by w1ng** [comment]
use the 2.0.12 SDL2 development library
not latest

**Comment by farism** [comment]
> use the 2.0.12 SDL2 development library not latest

Thank you, this worked for me

**Comment by LiuOcean** [comment]
> ![image](https://user-images.githubusercontent.com/5110979/137261826-3a1332cd-7a42-4af1-b0e6-6578a195e629.png)
> It's worked on SDL2-2.0.16.dmg

This also work on Mac 12.0 Apple Silicon. Thanks.
