### ISSUE TITLE
Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR SDL2_SDLMAIN_LIBRARY

### ISSUE THREAD

**Issue by bigofsmall** [recastnavigation/recastnavigation#490]
I follow the step as README.

1 Grab the latest SDL2 development library release from here and unzip it RecastDemo\Contrib. Rename the SDL folder such that the path RecastDemo\Contrib\SDL\lib\x86 is valid.

---------I create the folder path as above "D:\recastnavigation-master\RecastDemo\Contrib\SDL\lib\x86", and copy the SDL2.dll to x86 folder.

2 Run "premake5" vs2019 from the RecastDemo folder

---------I downlload the "premake5.exe", put it in "D:\recastnavigation-master\RecastDemo", run "premake5" vs2019.

3 Open the solution, build, and run.

---------Show error : 
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR SDL2_SDLMAIN_LIBRARY)		
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake	230

Thanks in advance.

**Comment by adamenkov** [comment]
Just curious,

1.  Do you have all four files in
D:\recastnavigation-master\RecastDemo\Contrib\SDL\lib\x86,
SDL2.dll
*SDL2.lib*
SDL2main.lib
SDL2test.lib
?

Evgeny

**Comment by adamenkov** [comment]
Also, you'll need to make sure your VS 2019 knows that it has to link the
.lib-files (I fed both: SDL2.lib;SDL2main.lib) and knows where to get them.

Evgeny

**Comment by bigofsmall** [comment]
I only download "SDL2.dll" , where can I get other lib :*SDL2.lib*,SDL2main.lib,SDL2test.lib.

Also, how to make vs2019 knows to links the .lib-files?
---------
Also, you'll need to make sure your VS 2019 knows that it has to link the
.lib-files (I fed both: SDL2.lib;SDL2main.lib) and knows where to get them.

Thanks again.

**Comment by adamenkov** [comment]
Are you sure you downloaded the development version of SDL?

Evgeny

**Comment by bigofsmall** [comment]
Sorry, I download wrong file and missing other lib you said above. I put them all to "D:\recastnavigation-master\RecastDemo\Contrib\SDL\lib\x86".
But still have the same proble,

**Comment by adamenkov** [comment]
You may want to carefully repeat the steps from the beginning.

If it doesn't help, you may want to add a location of files (that are
needed for CMake (premake) but can't be found) in the PATH environment
variable.

Later, in the C++ project for RecastDemo, you'll need to make sure the SDL
.lib files are fed to the linker.

Evgeny
