### ISSUE TITLE
How to draw grid lines every cell size on the ground ?

### ISSUE THREAD

**Issue by stu-GYULA** [recastnavigation/recastnavigation#491]
I wannna draw grids lines every cell size on the ground，but presently in recastDemo the distance between lines is likely ten times of cell size. How to draw grid lines every cell size?

**Comment by adamenkov** [comment]
You can adjust it in the following line

const float texScale = 1.0f / (m_cellSize * 10.0f);

(there are three copies of it, for each sample type).

Evgeny

**Comment by stu-GYULA** [comment]
cool ! thanks a lot
