### ISSUE TITLE
undefined references when building

### ISSUE THREAD

**Issue by bmorel** [recastnavigation/recastnavigation#492]
Hello. I am trying to update daemonmap's versions of recastnavigation libraries (from several years), and when doing a debug build got undefined references to stuff linked to assertions which are used from inside recast. Daemonmap's code itself contains only one occurrence, which is rather easy to fix, but then the libraries themselves still do not build.

I could hunt the 4 references and patch them myself for the need, of course, but this will likely introduce future pain for other people when need to update arise again and so I would prefer to avoid that. It would also mean that other users of this lib are likely to  be annoyed by the same issue.

The documentation on this custom assert mechanism is rather terse, the readme does not includes the assert word, and overall grepping didn't helped me getting any clue about how to make the libraries building.
It is ok to provide a way to use custom assertions, but I think at least a default one should be provided, since people usually do not expect a library to be missing parts.

**Comment by grahamboree** [comment]
`rcAssert` is meant to wrap `assert.h` (part of the C standard library) so that people can provide their own custom assert functions instead, if desired.  This sounds like an issue with the build system configuration for daemonmap.  Could you post the specific error you're seeing?

**Comment by grahamboree** [comment]
Closing this as answered. Please open a discussion if you have further questions
