### ISSUE TITLE
corner case of simplifyContour

### ISSUE THREAD

**Issue by tinyleolin** [recastnavigation/recastnavigation#494]
I played with some obj file, and found that the generated navmesh has folding triangles.

The obj file content
```
# Blender v2.93.3 OBJ File: ''
# www.blender.org
mtllib Scene5_change.mtl
o Scene5_NavMesh
v 53.297348 7.417726 50.281681
v 53.297348 7.417726 50.281681
v 39.448456 7.377217 73.321388
v 37.172058 7.685066 44.602772
v 27.231949 7.583801 49.961674
v 25.858749 7.555446 53.635578
v 33.749252 7.377217 71.741585
v 24.112946 7.518991 55.620274
v 24.927155 7.547345 53.364185
v 32.598953 7.377217 71.729485
v 31.549850 7.377217 72.276283
v 30.905746 7.377217 73.325386
v 28.629349 7.377217 73.171486
v 30.788345 7.377217 73.766884
v 15.886246 7.393421 64.952888
v 19.470947 7.377217 72.738075
v 28.147354 7.377216 75.067192
v 18.182953 7.450130 57.625385
v 15.537857 7.409624 59.496677
v 53.297348 7.417726 50.281681
vn -0.0042 0.9999 0.0111
vn 0.0013 1.0000 0.0082
vn -0.0031 0.9999 0.0112
vn -0.0065 0.9999 0.0127
vn -0.0112 0.9999 0.0085
vn -0.0001 1.0000 0.0088
vn 0.0036 1.0000 0.0069
vn 0.0080 1.0000 0.0049
vn -0.0006 1.0000 0.0082
vn 0.0000 1.0000 0.0000
vn -0.0047 0.9999 0.0093
vn -0.0001 1.0000 0.0021
vn -0.0101 0.9999 0.0046
vn -0.0126 0.9999 0.0038
vn 0.0132 0.9999 0.0097
usemtl Default_OBJ
s off
f 5//1 3//1 4//1
f 5//2 6//2 3//2
f 6//3 7//3 3//3
f 7//4 6//4 8//4
f 9//5 8//5 6//5
f 10//6 7//6 8//6
f 11//7 10//7 8//7
f 11//8 8//8 12//8
f 13//9 12//9 8//9
f 14//10 12//10 13//10
f 13//11 8//11 15//11
f 13//12 15//12 16//12
f 17//10 13//10 16//10
f 8//13 18//13 15//13
f 19//14 15//14 18//14
f 4//15 3//15 20//15
l 2 20
l 20 1
```

The generation params different from default
```
Solo Mesh
Cell Size: 0.10
Radius: 0.0
```

I found that, the raw contours are still correct, but the contours go wrong.

The raw contours
![1629614047(1)](https://user-images.githubusercontent.com/44769204/130345102-61351aaa-8720-4052-88f9-f719da3b58ff.png)

The contours
![1629614088(1)](https://user-images.githubusercontent.com/44769204/130345151-8220c9a7-bf5d-4786-83b3-87fbd34a552c.png)

The simplified region edge goes to the left side of the vertex.

**Comment by grahamboree** [comment]
Hmm!  This does indeed seem to create some very small folded triangles along the overlapping contour that passes though the polygon.  This could either be an issue with the contour simplification process, a float inaccuracy issue, or both.

**Comment by memononen** [comment]
There's an assumption that the internal edges between regions can be represented straight line. This is not true in big open areas. I recommend tiles and monotone partitioning for most use cases, that combo behaves better.
