### ISSUE TITLE
PolyMesh vs PolyMeshDetail

### ISSUE THREAD

**Issue by kklouzal** [recastnavigation/recastnavigation#499]
I have attached two screenshots. The output of duDebugDrawPolyMesh and duDebugDrawPolyMeshDetail.
Are these expected results?
The detail mesh appears to be accurate:
![polymeshdetail](https://user-images.githubusercontent.com/2928845/142739318-e5280df6-ca39-4218-9d8f-97238a0e7e81.png)
Versus the non-detail mesh which looks awful:
![polymesh](https://user-images.githubusercontent.com/2928845/142739323-eac6c170-f903-4824-bd33-e05050bd1a34.png)

**Comment by grahamboree** [comment]
Hi!  It's hard to say just looking at your screenshots what's going on.  I suspect it may be related to the voxelization size parameters and agent movement settings parameters.
