### ISSUE TITLE
Could TileCache build pipeline add detailMesh option

### ISSUE THREAD

**Issue by mqingpromise** [recastnavigation/recastnavigation#505]
navmesh build by tilecache does not fit the ground as tilemesh do, especially at the stairs...

**Comment by mqingpromise** [comment]
Ok, nothing to do with detail mesh, it's just tilecache's bug! first, walkContour merge many vertex that should not merge (x-axis alignment or z-axis alignment), some vertex has height difference; second, distancePtSeg does not compute y difference. Hope it helps

**Comment by grahamboree** [comment]
Hi!  Thanks for reporting this.  Could you provide a case that reproduces the specific issue you're seeing and submit that as a new issue?
