### ISSUE TITLE
Question on vertices placement in poly meshes generated by Recast

### ISSUE THREAD

**Issue by Scony** [recastnavigation/recastnavigation#509]
Assuming I'm using `cs=0.3` and `ch=0.3` for building poly meshes - would it be valid to assume (for each poly mesh separately) that there will be at most 1 generated vertex per voxel in voxels grid with `0.3x0.3x0.3` voxels? 

I'm asking because I've been assuming that and in practice, it worked... until recently when I've found that for complex geometry it's not always the case, see e.g. this situation:
![cells](https://user-images.githubusercontent.com/1207385/150675787-a1f0b548-5490-41fa-8868-6ea313d8892c.png)
The white grid reflects the `cs` of Recast. Teal lines are the parts of mesh generated by Recast. In all cases except one, there is at most 1 vertex per cell.

@memononen or anyone?

**Comment by memononen** [comment]
The white grid does not seem to match the values you pass to recast. All the vertices should have same relation to the white grid (i.e. at center or at corners, depends how you aligned the grid).

**Comment by Scony** [comment]
@memononen okay, so you say my assumption is right and the only thing I did wrong is the offset of the white grid?

**Comment by memononen** [comment]
Recast puts the vertices at the corners of the voxels. I'm not sure how to translate to your assumption. Anyways, your grid does not look like it matches he cellsize that is passed to Recast. It looks like like the white grid size is 1.0, if the Recast cell size is 0.3.

**Comment by Scony** [comment]
@memononen thanks, I think it answers my question :) just one more thing - is it guaranteed that there will be at most 1 vertex per corner?

**Comment by memononen** [comment]
If the corner is at tile border, then there will be a vertex on each tile. Also if you have multiple levels in your navmesh, then looking from top down, there can be multiple vertices in the same place. Otherwise there should be just one per voxel corner.
