### ISSUE TITLE
run  failed on macos12.0.1

### ISSUE THREAD

**Issue by M20170924** [recastnavigation/recastnavigation#516]
Macos12.0.1  
Follow the OSX build description,I make the project successfully,but when I open the solution, build, and run was failed.

---------Show error :
<img width="833" alt="截屏2022-04-04 下午12 35 29" src="https://user-images.githubusercontent.com/32235793/161475149-e03e303c-0e74-4460-9b90-70a1cce86155.png">

the sdl2.framework links  has already repaired
<img width="659" alt="截屏2022-04-04 下午12 42 43" src="https://user-images.githubusercontent.com/32235793/161475316-81c43c18-cb67-4fa1-8069-615eb2ec45f0.png">

Thanks in advance

**Comment by Prin-E** [comment]
This is because SDL2 is trying to initialize Metal render driver instead of OpenGL render driver.
Resolved in #513. Please update to the latest main branch!
