### ISSUE TITLE
How to fix this problem on macOS, when I use RecastDemo?

### ISSUE THREAD

**Issue by asciima** [recastnavigation/recastnavigation#523]
<img width="1200" alt="second" src="https://user-images.githubusercontent.com/7532774/167893675-b0baef5b-3dd9-4a42-9259-708d816158c8.png">

**Comment by Prin-E** [comment]
It looks like latest SDL2.0.22 causes this problem (works fine with 2.0.20 or older version). Commenting a line 

main.c:130 
`SDL_GL_CreateContext(window);`

will solve the problem. It happens because SDL has 2 GL contexts (SDL_CreateWindowAndRenderer() also creates GL context internally)

**Comment by grahamboree** [comment]
Closing, as RecastDemo works out of the box for me with [SDL 2.24.0](https://github.com/libsdl-org/SDL/releases/tag/release-2.24.0) and macOS 12.6
