### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_{INCLUDE,LIB}DIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [recastnavigation/recastnavigation#524]
As per title: `CMakeLists.txt` has
```
set(prefix ${CMAKE_INSTALL_PREFIX})
set(exec_prefix "\${prefix}")
set(libdir "\${exec_prefix}/${CMAKE_INSTALL_LIBDIR}")
set(bindir "\${exec_prefix}/${CMAKE_INSTALL_BINDIR}")
set(includedir "\${prefix}/${CMAKE_INSTALL_INCLUDEDIR}")
```
and so can’t handle absolute paths in `CMAKE_INSTALL_{INCLUDE,LIB}DIR` (whereas `bindir` is set but does not seem to be used anywhere?). This leads to broken .pc files on NixOS in particular.

See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

(Pkg-config files seem to be installing fine for me, so I’d guess that means #472 is fixed?)

**Comment by elsid** [comment]
Could you share the pkg-config file which you consider to be broken and CMake command to build recastnavigation? It's not very clear what do you mean by "broken". Could you describe your expectations and how they are different from what you have now?
