### ISSUE TITLE
Read access violation

### ISSUE THREAD

**Issue by zajo** [recastnavigation/recastnavigation#527]
On this line: https://github.com/recastnavigation/recastnavigation/blob/master/Recast/Source/RecastArea.cpp#L78

I hope I can get some hints on what to investigate. Unfortunately I am not able to provide the data that triggers it; I'm feeding Recast a rather large number of triangles.

Here is what `chf` is at the time of the crash:

```
-		chf	{width=59644 height=14159 spanCount=601645433 ...}	rcCompactHeightfield &
		width	59644	int
		height	14159	int
		spanCount	601645433	int
		walkableHeight	10	int
		walkableClimb	4	int
		borderSize	0	int
		maxDistance	0	unsigned short
		maxRegions	0	unsigned short
+		bmin	0x000002093f9b05bc {-8091.71484, -12595.8555, -1455.68506}	float[3]
+		bmax	0x000002093f9b05c8 {9801.50195, 7591.82520, 2791.87354}	float[3]
		cs	0.300000012	float
		ch	0.200000003	float
+		cells	0x0000020e3b616070 {index=0 count=0 }	rcCompactCell *
+		spans	0x0000020f04ba0070 {y=8191 reg=0 con=262145 ...}	rcCompactSpan *
+		dist	0x0000000000000000 {???}	unsigned short *
+		areas	0x00000210239e7070
```

Other variable names: `x: 26734`, `y: 0`, `i:0`, `nx: 26734`, `ny: -1`, `dir: 3`.

**Comment by memononen** [comment]
That is too large heightfield, use tiles instead. Recast supports only 2^24 spans.

**Comment by zajo** [comment]
Can you provide more details please, where can I read about the difference?

**Comment by memononen** [comment]
Take a look at the tile example.

**Comment by zajo** [comment]
OK so looking at the Sample_TileMesh::buildTileMesh function, it seems it builds a heightfield similarly to the Sample_SoloMesh code, and it also calls the rcErodeWalkableArea function which is crashing in the Sample_SoloMesh example. Please confirm that that's still OK?

**Comment by memononen** [comment]
You are allocating too big heighfield: 59644 x 14159 (should be < 1000x1000). The tiling approach divides the world into smaller heigh fields, which allows it to process really big worlds.
