### ISSUE TITLE
Why diagonal only check i's neighbour point in isCone?

### ISSUE THREAD

**Issue by liubai01** [recastnavigation/recastnavigation#528]
https://github.com/recastnavigation/recastnavigation/blob/c187b7e88bfc922bca2175e3751881bdf378ff0d/Recast/Source/RecastMesh.cpp#L287

Why here 
```cpp
// Returns true iff the diagonal (i,j) is strictly internal to the 
// polygon P in the neighborhood of the i endpoint.
static bool	inCone(int i, int j, int n, const int* verts, int* indices)
{
	const int* pi = &verts[(indices[i] & 0x0fffffff) * 4];
	const int* pj = &verts[(indices[j] & 0x0fffffff) * 4];
	const int* pi1 = &verts[(indices[next(i, n)] & 0x0fffffff) * 4];
	const int* pin1 = &verts[(indices[prev(i, n)] & 0x0fffffff) * 4];

	// If P[i] is a convex vertex [ i+1 left or on (i-1,i) ].
	if (leftOn(pin1, pi, pi1))
		return left(pi, pj, pin1) && left(pj, pi, pi1);
	// Assume (i-1,i,i+1) not collinear.
	// else P[i] is reflex.
	return !(leftOn(pi, pj, pi1) && leftOn(pj, pi, pin1));
}

// Returns T iff (v_i, v_j) is a proper internal
// diagonal of P.
static bool diagonal(int i, int j, int n, const int* verts, int* indices)
{
	return inCone(i, j, n, verts, indices) && diagonalie(i, j, n, verts, indices);
}
```
Only check vertex i's neighbour points. How about j's neighbour point?  It is possible that j's next point inside the ear and it could pass the diagonalie check since (j, j+1) is skipped in `diagonalie`.

**Comment by memononen** [comment]
The algorithm comes from "Computational Geometry in C", which has in depth explanation of it.

**Comment by liubai01** [comment]
Thanks

**Comment by liubai01** [comment]
In originial implementation in "Computational Geometry in C", it  checks both direction

```cpp
/*---------------------------------------------------------------------
Returns TRUE iff (a,b) is a proper internal diagonal.
---------------------------------------------------------------------*/
bool	Diagonal( tVertex a, tVertex b )
{
   return InCone( a, b ) && InCone( b, a ) && Diagonalie( a, b );
}
```
You would see `InCone (a,b)` and `InCone(b, a)`. But the adapted version in recast only checks one direction.

**Comment by liubai01** [comment]
![image](https://user-images.githubusercontent.com/10471419/184057450-886f504e-c7a1-4d52-ab31-75538e358fe5.png)

It would sometime lead to the overlap triangles (not a fatal bug). I am still trying to somehow stably reproduce this issue.

**Comment by memononen** [comment]
Good catch, I cannot remember if there was a reason to omit the other direction.

The double triangle bug you're seeing comes from the detail mesh triangulation, which is not very robust.

**Comment by SongsMin** [comment]
When j "isCone" with i's neighbour points and i is not with j's, ij must intersect with some edge(s) which checked by "diagonalie".

**Comment by liubai01** [comment]
I agree with @SongsMin. 

`Diagonalie(a, b)` makes sure the diagonal would not intersect with any edge, which further indicates ab is either an external or internal diagonal. Therefore, in this case of `Diagonalie(a, b)` is `True` iff XOR(`isCone(a, b)`, `isCone(b, a)`) is `False`.

![image](https://user-images.githubusercontent.com/10471419/197362923-404df2c3-0106-40df-b3f0-13dfcfa2e347.png)
 
I check the original material "Computational Geometry in C". It said in 1.6.3 Diagonal (p35) that

> If either `IsCone(a, b)` and `isCone(b, a)` returns false, the (potentially) expensive `Diagonalie` check will not be executed.

Therefore, Recast implementation `InCone(a, b) && Diagonalie(a, b)` could indeed guarantee the internal diagonal, while `isCone(b, a)` is somehow a potential improvement.

It is reasonable to remove `isCone(b, a)` without influencing correctness.

Thanks again for @memononen 's reference to the original material. It helps me a lot.
