### ISSUE TITLE
[DetourNavMesh.h][dtMeshTile] Is the size described in comment wrong?

### ISSUE THREAD

**Issue by pineappleKID** [recastnavigation/recastnavigation#535]
master link: https://github.com/recastnavigation/recastnavigation/blob/master/Detour/Include/DetourNavMesh.h#L288
permalink: https://github.com/recastnavigation/recastnavigation/blob/9dc88fcab98b2213e88f7bbe5a3354ffc70c59bc/Detour/Include/DetourNavMesh.h#L288

However, `verts` in `dtMeshTile` should be like **[(x, y, z) * dtMeshHeader::vertCount]** thus the size should be **[3 * dtMeshHeader::vertCount]**.
For example, it is used as https://github.com/recastnavigation/recastnavigation/blob/c187b7e88bfc922bca2175e3751881bdf378ff0d/Detour/Source/DetourNavMesh.cpp#L584
where `dtPoly::verts` indicates the vertex index.

**Comment by grahamboree** [comment]
Yep, this indeed seems wrong!  Feel free to send over a PR with the fix :)
