### ISSUE TITLE
NavMesh.connectExtLinks occasional failure

### ISSUE THREAD

**Issue by bradrobnett** [recastnavigation/recastnavigation#537]
Connections between tiles are usually pretty solid in my use of the Java port of Recast, but there are cases where polygon tessellation doesn't quite match up between neighboring tiles. As a result, there are occasionally regions that do not allow pathing where they should.

Is this already a known issue with a workaround?
If not, is there some already existing, reliable way to snap vertices together across the tile boundary (or create new vertices) to fix the issue?

I have traced the code responsible for ensuring cross-tile connections to NavMesh.connectExtLinks() and don't see any current provisions for vertex modification there. Just want to make sure I'm not missing some solution that already exists.

**Comment by memononen** [comment]
Detour allows slight mismatch between the tiles. When ext links are connected, we'll match the overlap between the edges and store that along with the link.

**Comment by bradrobnett** [comment]
Thanks for the quick response, Mikko!
Can you direct me to the code in Detour that does this? I'm using a custom pathfinder that doesn't have this feature.
