### ISSUE TITLE
CMake SDL2 include paths missing on macOS

### ISSUE THREAD

**Issue by grahamboree** [recastnavigation/recastnavigation#577]
## Setup:
m1 MacBook Pro
macOS 13.0
SDL2.framework installed to /Library/Frameworks

## Repro:
build with the following commands run from the root of a clean copy of the repo
```
cmake -B ./build -DCMAKE_BUILD_TYPE=Debug
cmake --build ./build --config Debug
```

results in:
```
...
[ 60%] Building CXX object RecastDemo/CMakeFiles/RecastDemo.dir/Source/ConvexVolumeTool.cpp.o
In file included from /Users/grahampentheny/workspace/recastnavigation/RecastDemo/Source/ConvexVolumeTool.cpp:24:
/Library/Frameworks/SDL2.framework/Headers/SDL.h:32:10: fatal error: 'SDL2/SDL_main.h' file not found
#include <SDL2/SDL_main.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [RecastDemo/CMakeFiles/RecastDemo.dir/Source/ConvexVolumeTool.cpp.o] Error 1
make[1]: *** [RecastDemo/CMakeFiles/RecastDemo.dir/all] Error 2
make: *** [all] Error 2
```

I suspect this line in `RecastDemo/CMakeLists.txt` is to blame, though I'm not sure how frameworks are handled by cmake.
```
include_directories(Contrib/SDL/include)
```

---

## Fix Requirements:
We ultimately need the cmake script to invoke clang with the `-framework SDL2` and `-I/Library/Frameworks/SDL2.framework/Headers` options.  

It would also be nice to be able to specify the SDL framework path (via `-F` clang flag) so it's not just hardcoded to `/Library/Frameworks`.  Specifying the framework path like this is useful for CI processes that might not want to or be able to muck about in `/Library`.

**Comment by elsid** [comment]
There is `SDL2_ROOT_DIR` variable to provide a path to SDL2. Run CMake using it to make CMake find the library:
```
cmake -D SDL2_ROOT_DIR=<path> <...>
```

I have no way to test this on macOS but I see [some support](https://github.com/recastnavigation/recastnavigation/blob/b0d71bed92a89c0b4ad63ca4278d12c63d8d6eb4/RecastDemo/cmake/FindSDL2.cmake#L82-L102) for the frameworks in the FindSDL2.cmake.

`include_directories(Contrib/SDL/include)` has no effect here. `include_directories` just adds another include directory to the complier command. It does not exclude any other added directories. Also there is noting at this location in this repository. You can ask author of the [related change](https://github.com/recastnavigation/recastnavigation/pull/454) why they added it.

**Comment by grahamboree** [comment]
Thanks for the info!

> There is SDL2_ROOT_DIR variable to provide a path to SDL2
Sorry I should have been more clear.  I can get past the configure step of cmake with SDL in `/Library/Frameworks`.  It clearly finds the library because if I remove SDL from that path I get a specific error saying it can't find SDL.  The issue here is that even when the library is found, the include paths aren't configured correctly, which is why the ConvexVolumeTool can't find `SDL_main.h`.

> You can ask author of the https://github.com/recastnavigation/recastnavigation/pull/454 why they added it.
This is the include path for SDL on Windows.  The reason I mentioned it is that it looks like it's not being set differently for different platforms.  I understand that adding an additional `-I` path won't cause any major issues if it doesn't exist, just pointing out that maybe there's a missing platform switch here.
