### ISSUE TITLE
Impromptu fix for off-mesh connections with long distance

### ISSUE THREAD

**Issue by niji-k** [recastnavigation/recastnavigation#586]
![image](https://user-images.githubusercontent.com/119095278/204074851-5bb7e1a5-54d2-4d8c-91aa-e4155ee15412.png)

I'm a junior developer, using Recast Navigation for my group's game.
I was told that these off-mesh connections won't work with long distances between endpoints, and that the level designer must adjust the tile size manually to make it work.

After some googling and reading through lines of code, I realized that these connections would only work if they are within a single tile, or connecting two adjacent tiles. I presume this is probably to block issues that could emerge when trying to add connection(s) before the two tiles containing two endpoints of said connection are fully loaded.

I was able to produce a working fix, by forcing the code to add connection after all tiles are fully loaded.
This fix is impromptu as the title suggests, and if my testing is right, it does not guarantee that the path is optimal.
Please take a look at this commit made to a fork, and tell me what you think about it: https://github.com/niji-k/recastnavigation/commit/13eb591b1b752de2e5a78137580b7aeec106eeab

Below are screenshots made while testing, showing some possible cases with modified behavior from this fix.
![image](https://user-images.githubusercontent.com/119095278/204075276-9ce5160c-fb8a-4eff-9ad2-f1535e692131.png)
(Pathfinding successfully utilized the off-mesh connection given.)

![image](https://user-images.githubusercontent.com/119095278/204075383-98807eea-acd7-4f0c-8861-bc67f9536c73.png)
(Suboptimal path: I have no idea why the connection isn't used.)

![image](https://user-images.githubusercontent.com/119095278/204075620-d74914ab-cbd5-4f40-83ab-8b92266499f5.png)
![image](https://user-images.githubusercontent.com/119095278/204075626-d394da38-b15a-4a7e-92c3-64bd53bc1799.png)
(One-way connections can also be used: notice how swapping the start/end pos changes the path.)

P.S. I'm definitely new to this Github stuff, let alone Git, so any advices regarding the Github workflow is highly appreciated.

**Comment by grahamboree** [comment]
Thanks for this!  Could you instead submit this as a pull request?  There's some documentation [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to do that in GitHub.
