### ISSUE TITLE
the Epsilon in DetourCommon/dtIntersectSegmentPoly2D

### ISSUE THREAD

**Issue by azurepine** [recastnavigation/recastnavigation#607]
https://github.com/recastnavigation/recastnavigation/blob/3c4a34968afab75a0a041cf8cd8f47e2fe6158a6/Detour/Source/DetourCommon.cpp#L115

0.00000001 seems to be smaller than the typical machine epsilon for 32-bit floating-point numbers, 
which is around 1.19 x 10^-7.

**Comment by grahamboree** [comment]
Hmm!  Yeah it does look like it's an order of magnitude or two too small at least according to [wikipedia](https://en.wikipedia.org/wiki/Machine_epsilon).  Thankfully this is only used as an optimization in the segment-polygon intersection test when the segment is parallel to a polygon edge, so at worst it's only causing minor perf problems.  I'll increase the epsilon to something a bit bigger.  Thanks for pointing this out!
