### ISSUE TITLE
Update vcpkg with 1.6.0

### ISSUE THREAD

**Issue by grahamboree** [recastnavigation/recastnavigation#630]
Admittedly I have no idea how vcpkg works and after taking a look through the docs it's way more complex than I really care to spend an afternoon learning just for this one thing.

@ivysnow, @JackBoosY, @phisko, seems like ya'll have been maintaining the recast vcpkg port entry.  Can you either update it to 1.6.0 or point me in the right direction here?

**Comment by JackBoosY** [comment]
Updated.

**Comment by grahamboree** [comment]
Thank you! 🙏
