### ISSUE TITLE
Implementation for Rust

### ISSUE THREAD

**Issue by nightactive-git** [recastnavigation/recastnavigation#631]
Hey everyone,

this project looks very sophisticated. Do you plan an implementation for Rust? 
There are a few navigation solutions for rust/bevy out there, but they all have there problems and aren't reliable. A reliable navmesh generator for Rust would be a game changer for a lot of Rust game developer. 

Kind regards!

**Comment by MaxHayman** [comment]
You could just write your own wrapper and compile recast into a dll and call it yourself. It's what I am currently doing for C#.

**Comment by grahamboree** [comment]
Hi!  Just wanted to give a semi-official underline to Max's response.  We don't have plans to implement a Rust version, but if that sounds interesting you're absolutely welcome to start a port.  I know of a few unofficial ports out there.  Mostly as part of other 3rd party packages.  For example, there are ports to C# for some packages on the Unity asset store.  There are also plenty of people who have integrated Recast into non-C++ projects by creating a small C API, bundling it in a DLL and accessing it through their language of choice's FFI.

There's been some discussion internally about potentially moving Recast from C++ to C with the intention of making other language bindings easier.  At the very least, offering an official C API to bind to makes a ton of sense.  At the moment however Recast is primarily a C++ library.

**Comment by SlimeYummy** [comment]
Maybe this reply is a little late.

Recastnavigation is cool. So I'm writing a Rust wrapper for recastnavigation. Considering the amount of code in Recastnavigation, I have no plan to rewrite full project in Rust, but I want to wrap as much of the API as possible.
The repo is here [recastnavigation-rs](https://github.com/SlimeYummy/recastnavigation-rs) .
