### ISSUE TITLE
TempObstacles  problem on stair

### ISSUE THREAD

**Issue by WMQing** [recastnavigation/recastnavigation#658]
tri mesh like this:
# stair.obj
v 50 0 0
v 50 0 50
v 151 100 50
v 151 100 0
v 0 0 0
v 0 0 50
f 1 2 3
f 1 3 4
f 1 5 6
f 1 6 2
use TempObstacles option build(i.e with TileCache)， got navmesh like this:
![image](https://github.com/recastnavigation/recastnavigation/assets/14830742/1fe9ee50-7a49-49af-840e-2426c6b67946)
this is bad, hope fix it.

**Comment by grahamboree** [comment]
Hi!  The resulting navmesh depends quite heavily on the parameters you supply recast.  It looks like you might be using a large cell size in the rasterization step which is smoothing over all but coarse-grained details. 

For example, using the default settings in RecastDemo, I was able to build the following navmesh with the obj you provided.  

<img width="1039" alt="Screenshot 2024-01-01 at 1 29 09 PM" src="https://github.com/recastnavigation/recastnavigation/assets/1139220/4ba5423f-d42d-4061-9ff6-cddc8ca6dc62">

I'd suggest exploring your Recast build settings and how they affect the output mesh.
