### ISSUE TITLE
Bug while loading vertices/indices

### ISSUE THREAD

**Issue by ItzzFdr** [recastnavigation/recastnavigation#690]
So I was trying to load a .obj file full of vertices/indices and seems like something is very wrong.

The floor seems to be ignored by OpenGL and recast, also cannot generate navmesh for the floor plane or house floor, only for top structures (high points)
But the floor can be seen if looking from below to upwards

<img width="898" alt="Screenshot_1" src="https://github.com/recastnavigation/recastnavigation/assets/154404218/83322820-8f22-408c-a6bd-81ad0f78af92">
<img width="891" alt="Screenshot_2" src="https://github.com/recastnavigation/recastnavigation/assets/154404218/e4e44388-7405-4763-9516-1402ed6dfc6b">
<img width="906" alt="Screenshot_4" src="https://github.com/recastnavigation/recastnavigation/assets/154404218/620c3984-9775-4dc4-9a17-418fed61f2ad">

I though it was some problem with the .obj file, but blender could render it without any problems

<img width="575" alt="Screenshot_3" src="https://github.com/recastnavigation/recastnavigation/assets/154404218/998b344a-8638-4206-ad41-4664d7857167">

If anybody can help me, below is the level.obj file
[level.zip](https://github.com/recastnavigation/recastnavigation/files/14317975/level.zip)

**Comment by liubai01** [comment]
It seems taht the cell size is a little bit large.

**Comment by grahamboree** [comment]
As was already stated, if you're getting things rendering by disabling backface culling, that implies that your normals or winding order is wrong for the floor.  Also keep in mind that RecastDemo is just a demo.  It doesn't have the most robust obj loading code, so it's possible there's a bug somewhere there as well.
