### ISSUE TITLE
[Github Action] Segmentation fault, process completed with exit code 139

### ISSUE THREAD

**Issue by SlimeYummy** [recastnavigation/recastnavigation#694]
Hello everyone.
Sometimes, I see the following error in github actions, Tests workflow.
```
Run ./Tests --verbosity high --success
/home/runner/work/_temp/940daf06-485f-4ee4-b6ee-b6610228a62d.sh: line 1:  3452 Segmentation fault      (core dumped) ./Tests --verbosity high --success
Error: Process completed with exit code 139.
```
I tried uploading the core dump as an artifact but failed.
Does anyone know why these errors occur? Does it imply that the project has an error such as array out-of-bounds?

**Comment by grahamboree** [comment]
Yeah likely there's some memory error that's causing a crash. I'll try to get asan an ubsan working with the test executable and see if that helps find the problem.

**Comment by grahamboree** [comment]
Hmm seems like it's a GH Actions issue.  Will investigate further if it crops up again.
