### ISSUE TITLE
Unable to Export Off-Mesh Links in recastdemo Temp Obstacles

### ISSUE THREAD

**Issue by xiaokang5350** [recastnavigation/recastnavigation#695]
I've been experimenting with recastdemo Temp Obstacles and encountered an issue regarding the export of off-mesh links. It seems that the current functionality does not support exporting off-mesh links.

**Comment by grahamboree** [comment]
Hi!  RecastDemo was originally created to just showcase the functionality of Recast, not be a full-featured navmesh editing system.  As such it's probably missing a lot of information in the serialization system.  I'd like to work towards a more substantial navmesh editing system in the future, but for now it's just a showcase of the API usage.
