### ISSUE TITLE
Live Changelog Markdown Rendering has error

### ISSUE THREAD

**Issue by anranlee99** [recastnavigation/recastnavigation#712]
https://recastnav.com/md_CHANGELOG.html#:~:text=%3Ca%20href%3D%22https,2023%2D05%2D21

In Changelog.md the markdown displays fine, but on the live site, the rendered HTML is not displaying correctly. 
![image](https://github.com/recastnavigation/recastnavigation/assets/93017513/72b97c06-0c37-4748-9d9c-e5da112cb7bf)

**Comment by grahamboree** [comment]
Fixed in `8c8df4881165aa70c117213a64b11d84cfa65180`
