### ISSUE TITLE
RecastDemo seems broken (no agents or pathfinding shown)

### ISSUE THREAD

**Issue by Kleenox** [recastnavigation/recastnavigation#714]
I built the RecastDemo with cmake in visual studio. I'm using 1.6.0 because I was after using a stable build. It runs, it displays the meshes but the pathfinding doesn't work, I set the start and end points and nothing happens. Is this a known issue? Apologies if already reported, I searched as well as I could and found nothing.

**Comment by grahamboree** [comment]
I've been there.  No worries!  ❤️
