### ISSUE TITLE
Bug in dtNavMeshQuery::moveAlongSurface

### ISSUE THREAD

**Issue by bryanmcconkey** [recastnavigation/recastnavigation#73]
In our game we use moveAlongSurface for most of our entity movements, which works well in most situations. The fact that it uses the closest point to the destination works very well for us in allowing us to 'slide' along a wall of the nav mesh as long as the inputted movement is on a angle to the wall.

However, I had a few bug reports from people saying occasionally (pretty rare in our game) there would be a section of the map which they could not slide along the edge. They would be stuck in the same location as long as there was any delta off the wall edge. After some extensive debugging I have found what seems to be happening, and have a fix for the scenario, but I wanted to first discuss to make sure what I am seeing is correct.

At a high level what seems to be happening is that not all edges that need to be checked for closest points are being checked. Specifically on tile boundaries. When the edge is a tile border (found with DT_EXT_LINK) the linked poly ref gets added, but the edge is not checked for distance. While this makes sense for internal edges (as they will always have a poly on the other side which shares that edge completely) on tile boundaries it does not seem to be the case. I am seeing a tile boundary edge that links to a poly in the adjacent tile with an edge not covering the full span of the source edge. (say the source edge is 100 units, the shared edge in another tile is for example only 50). As the source edge is not checked against for nearest distance, and the full length of the edge does not exist in the adjacent tile, there is a portion of a wall which is never checked against. In the case where that portion is where the closest point would lie, I am instead getting a result of the closest point is the origin point, and thus the player can not move.

When i change the function to also check for nearest distance on tile boundary edges, everything works as expected and it finds the correct closest point.

I'll happily create a pull request with the changes I have done to resolve this scenario, but I wanted to first make sure that its a valid scenario to have a tile boundary edge not fully shared by their linked poly in another tile. If this is normal then I suspect there may be other rare cases where similar errors could be hit such as in dtNavMeshQuery::findDistanceToWall where tile border edges are not considered walls if they link to an adjacent tile's poly. If the adjacent tile's poly only partially covers the edge, then a portion of that edge should be considered a 'wall'.

I've attached a marked up screenshot illustrating the situation (which i used to debug my issue once i found a repo case).  The dashed orange line shows where a tile boundary is. The small red line inside the red circle is the startPos to endPos (the res circle being the searchPos and searchRad as determined in moveAlongSurface): Player starting on the poly vertex, and trying to move down left (which is expected to slide downwards along that vertical wall). The pink line (under the orange dotted one) highlights the boundary edge of the origin poly which is NOT checked for closest distance. Please note the poly which that boundy edge links to on the left side of the orange line shares only a portion of the edge.

![detourbug](https://cloud.githubusercontent.com/assets/6762852/5668694/6ff8cf06-973f-11e4-8d0d-11065a56c757.png)

Bryan McConkey

**Comment by bryanmcconkey** [comment]
So after some additional investigation I think the source of my problem here was the tiles were not generating with identical area ids for their cells in all cases. Fixing this seems to have resulted in the tile boundary polys always sharing edges perfectly (at least in all cases I have seen so far) and thus my changes don't seem required.

I will keep an eye out for any more problems, but I suspect that was the only real problem. It would be good if there was some debug option to validate the mesh for cases like this.

**Comment by hymerman** [comment]
Can this be closed, @bryanmcconkey?

**Comment by bryanmcconkey** [comment]
Yes, this issue has not cropped up again.
Closing.
