### ISSUE TITLE
Is there any way to currently use Recast/Detour outside of C++?

### ISSUE THREAD

**Issue by ghostbutter-games** [recastnavigation/recastnavigation#742]
Hello,

I would really like to use Recast/Detour from my custom 3D engine, but unfortunately I can't generate bindings from the .dylib I managed to build with CMake (the names are mangled)

I then read the docs on the website that told me this exact thing, and it also said that there were some projects that managed to create working bindings.

The only ones I managed to find were the C# and Java ports, which I also can't use from my project.

Is there any hope for me, or am I just out of luck here?
If so: Do you have any recommendations for an alternative to Recast/Detour?

Any help would be greatly appreciated.

**Comment by grahamboree** [comment]
Hi!  Unfortunately Recast is C++ only at the moment.  You can make your own C wrapper (this is what most other language ports have done) and bind to that.  Converting the library to C is on the roadmap but not implemented yet.
