### ISSUE TITLE
off-mesh connections only make link with neighbors in tiled mesh.

### ISSUE THREAD

**Issue by ranbochen** [recastnavigation/recastnavigation#80]
if off-mesh start-point end-point in different tile,
and the tiles are not neighbors, 
the off-mesh connection does not work.
(start-point is correct, end-point  is drawn in red circle )

in dtNavMesh::addTile
// Connect with neighbour tiles. 
connectExtOffMeshLinks

in DetourDebugDraw.drawMeshTile
endSet is false

**Comment by memononen** [comment]
This is by design.

**Comment by ranbochen** [comment]
Oh! 
My project needs long way connections, so i find this issue.
If it's by design, i'll make a personal patch to make it functional.
Thanks for helping.
Thanks for the awesome project.
