### ISSUE TITLE
How can I display CJK strings?

### ISSUE THREAD

**Issue by J-Liu** [recastnavigation/recastnavigation#96]
I notised Recast implemented a IMGUI, how can I display CJK strings in it?

**Comment by memononen** [comment]
Unfortunately, I took  a shortcut and the font rendering supports only the basic western characters.

If you feel adventurous, you could try to add https://github.com/memononen/fontstash
It supports CJK strings as long as the they are in UTF8 and the font supports it.

**Comment by J-Liu** [comment]
Thank you, font stash is cool!

And I find you have a IMGUI at https://github.com/memononen/milligui , it is pretty cool too, will you continue working on it?

**Comment by memononen** [comment]
I may pick it up again one day, but right now I don't have time. If you're looking for actively developed immediate mode UI library, I recommend this one: https://github.com/ocornut/imgui

**Comment by J-Liu** [comment]
Thank you. I'll make a try on it.
